/* Generated by Spinel AOT compiler */
#include "sp_runtime.h"
/* sp_sym intern table */
#define SP_SYM_COUNT 61
static const char *const sp_sym_names[61] = {(&("\xff" "nfkc")[1]),(&("\xff" "vocabulary")[1]),(&("\xff" "word_to_index")[1]),(&("\xff" "scale")[1]),(&("\xff" "norm1_gamma")[1]),(&("\xff" "w_q")[1]),(&("\xff" "w_k")[1]),(&("\xff" "w_v")[1]),(&("\xff" "w_o")[1]),(&("\xff" "norm2_gamma")[1]),(&("\xff" "w_ff1")[1]),(&("\xff" "w_ff2")[1]),(&("\xff" "vocab_size")[1]),(&("\xff" "d_model")[1]),(&("\xff" "d_ff")[1]),(&("\xff" "n_heads")[1]),(&("\xff" "context_length")[1]),(&("\xff" "n_layers")[1]),(&("\xff" "token_ids")[1]),(&("\xff" "blocks")[1]),(&("\xff" "start_pos")[1]),(&("\xff" "x_embed")[1]),(&("\xff" "x_out")[1]),(&("\xff" "x_block_out")[1]),(&("\xff" "x_final")[1]),(&("\xff" "rms_final")[1]),(&("\xff" "logits")[1]),(&("\xff" "rms1")[1]),(&("\xff" "h_norm1")[1]),(&("\xff" "attn_cache")[1]),(&("\xff" "x_attn")[1]),(&("\xff" "rms2")[1]),(&("\xff" "h_norm2")[1]),(&("\xff" "ff_cache")[1]),(&("\xff" "query_offset")[1]),(&("\xff" "q")[1]),(&("\xff" "k")[1]),(&("\xff" "v")[1]),(&("\xff" "attn")[1]),(&("\xff" "out")[1]),(&("\xff" "per_head")[1]),(&("\xff" "concat")[1]),(&("\xff" "pre")[1]),(&("\xff" "hidden")[1]),(&("\xff" "token_embed")[1]),(&("\xff" "pos_embed")[1]),(&("\xff" "lm_head")[1]),(&("\xff" "norm_final_gamma")[1]),(&("\xff" "loss")[1]),(&("\xff" "pos_offset")[1]),(&("\xff" "layers")[1]),(&("\xff" "chomp")[1]),(&("\xff" "parameters")[1]),(&("\xff" "memory_kb")[1]),(&("\xff" "vocab")[1]),(&("\xff" "context")[1]),(&("\xff" "epochs")[1]),(&("\xff" "learning_rate")[1]),(&("\xff" "batch_size")[1]),(&("\xff" "max_tokens")[1]),(&("\xff" "temperature")[1])};
static const char *sp_sym_to_s(sp_sym id) __attribute__((unused));
static const char *sp_sym_to_s(sp_sym id){if(id>=0&&id<SP_SYM_COUNT)return sp_sym_names[id];return "";}
#define SPS_nfkc ((sp_sym)0)
#define SPS_vocabulary ((sp_sym)1)
#define SPS_word_to_index ((sp_sym)2)
#define SPS_scale ((sp_sym)3)
#define SPS_norm1_gamma ((sp_sym)4)
#define SPS_w_q ((sp_sym)5)
#define SPS_w_k ((sp_sym)6)
#define SPS_w_v ((sp_sym)7)
#define SPS_w_o ((sp_sym)8)
#define SPS_norm2_gamma ((sp_sym)9)
#define SPS_w_ff1 ((sp_sym)10)
#define SPS_w_ff2 ((sp_sym)11)
#define SPS_vocab_size ((sp_sym)12)
#define SPS_d_model ((sp_sym)13)
#define SPS_d_ff ((sp_sym)14)
#define SPS_n_heads ((sp_sym)15)
#define SPS_context_length ((sp_sym)16)
#define SPS_n_layers ((sp_sym)17)
#define SPS_token_ids ((sp_sym)18)
#define SPS_blocks ((sp_sym)19)
#define SPS_start_pos ((sp_sym)20)
#define SPS_x_embed ((sp_sym)21)
#define SPS_x_out ((sp_sym)22)
#define SPS_x_block_out ((sp_sym)23)
#define SPS_x_final ((sp_sym)24)
#define SPS_rms_final ((sp_sym)25)
#define SPS_logits ((sp_sym)26)
#define SPS_rms1 ((sp_sym)27)
#define SPS_h_norm1 ((sp_sym)28)
#define SPS_attn_cache ((sp_sym)29)
#define SPS_x_attn ((sp_sym)30)
#define SPS_rms2 ((sp_sym)31)
#define SPS_h_norm2 ((sp_sym)32)
#define SPS_ff_cache ((sp_sym)33)
#define SPS_query_offset ((sp_sym)34)
#define SPS_q ((sp_sym)35)
#define SPS_k ((sp_sym)36)
#define SPS_v ((sp_sym)37)
#define SPS_attn ((sp_sym)38)
#define SPS_out ((sp_sym)39)
#define SPS_per_head ((sp_sym)40)
#define SPS_concat ((sp_sym)41)
#define SPS_pre ((sp_sym)42)
#define SPS_hidden ((sp_sym)43)
#define SPS_token_embed ((sp_sym)44)
#define SPS_pos_embed ((sp_sym)45)
#define SPS_lm_head ((sp_sym)46)
#define SPS_norm_final_gamma ((sp_sym)47)
#define SPS_loss ((sp_sym)48)
#define SPS_pos_offset ((sp_sym)49)
#define SPS_layers ((sp_sym)50)
#define SPS_chomp ((sp_sym)51)
#define SPS_parameters ((sp_sym)52)
#define SPS_memory_kb ((sp_sym)53)
#define SPS_vocab ((sp_sym)54)
#define SPS_context ((sp_sym)55)
#define SPS_epochs ((sp_sym)56)
#define SPS_learning_rate ((sp_sym)57)
#define SPS_batch_size ((sp_sym)58)
#define SPS_max_tokens ((sp_sym)59)
#define SPS_temperature ((sp_sym)60)
static int sp_sym_sort_cmp(const void*a,const void*b) __attribute__((unused));
static int sp_sym_sort_cmp(const void*a,const void*b){return strcmp(sp_sym_to_s(*(const sp_sym*)a),sp_sym_to_s(*(const sp_sym*)b));}
static void sp_sym_array_sort(sp_IntArray*a) __attribute__((unused));
static void sp_sym_array_sort(sp_IntArray*a){qsort(a->data+a->start,a->len,sizeof(mrb_int),sp_sym_sort_cmp);}

typedef struct{sp_sym*keys;mrb_int*vals;sp_sym*order;mrb_int len;mrb_int cap;mrb_int mask;}sp_SymIntHash;
static void sp_SymIntHash_fin(void*p){sp_SymIntHash*h=(sp_SymIntHash*)p;free(h->keys);free(h->vals);free(h->order);}
static sp_SymIntHash*sp_SymIntHash_new(void){sp_SymIntHash*h=(sp_SymIntHash*)sp_gc_alloc(sizeof(sp_SymIntHash),sp_SymIntHash_fin,NULL);h->cap=16;h->mask=15;h->keys=(sp_sym*)malloc(sizeof(sp_sym)*h->cap);for(mrb_int i=0;i<h->cap;i++)h->keys[i]=-1;h->vals=(mrb_int*)calloc(h->cap,sizeof(mrb_int));h->order=(sp_sym*)malloc(sizeof(sp_sym)*h->cap);h->len=0;return h;}
static void sp_SymIntHash_grow(sp_SymIntHash*h){mrb_int oc=h->cap;sp_sym*ok=h->keys;mrb_int*ov=h->vals;h->cap*=2;h->mask=h->cap-1;h->keys=(sp_sym*)malloc(sizeof(sp_sym)*h->cap);for(mrb_int i=0;i<h->cap;i++)h->keys[i]=-1;h->vals=(mrb_int*)calloc(h->cap,sizeof(mrb_int));h->order=(sp_sym*)realloc(h->order,sizeof(sp_sym)*h->cap);h->len=0;for(mrb_int i=0;i<oc;i++){if(ok[i]>=0){mrb_int idx=(mrb_int)(((mrb_int)ok[i])&h->mask);while(h->keys[idx]>=0)idx=(idx+1)&h->mask;h->keys[idx]=ok[i];h->vals[idx]=ov[i];h->len++;}}free(ok);free(ov);}
static mrb_int sp_SymIntHash_get(sp_SymIntHash*h,sp_sym k){mrb_int idx=(mrb_int)(((mrb_int)k)&h->mask);while(h->keys[idx]>=0){if(h->keys[idx]==k)return h->vals[idx];idx=(idx+1)&h->mask;}return 0;}
static void sp_SymIntHash_set(sp_SymIntHash*h,sp_sym k,mrb_int v){if(h->len*2>=h->cap)sp_SymIntHash_grow(h);mrb_int idx=(mrb_int)(((mrb_int)k)&h->mask);while(h->keys[idx]>=0){if(h->keys[idx]==k){h->vals[idx]=v;return;}idx=(idx+1)&h->mask;}h->keys[idx]=k;h->vals[idx]=v;h->order[h->len]=k;h->len++;}
static mrb_bool sp_SymIntHash_has_key(sp_SymIntHash*h,sp_sym k){mrb_int idx=(mrb_int)(((mrb_int)k)&h->mask);while(h->keys[idx]>=0){if(h->keys[idx]==k)return TRUE;idx=(idx+1)&h->mask;}return FALSE;}
static mrb_int sp_SymIntHash_length(sp_SymIntHash*h){return h->len;}
static void sp_SymIntHash_delete(sp_SymIntHash*h,sp_sym k){mrb_int idx=(mrb_int)(((mrb_int)k)&h->mask);while(h->keys[idx]>=0){if(h->keys[idx]==k){h->keys[idx]=-1;h->vals[idx]=0;h->len--;mrb_int j=(idx+1)&h->mask;while(h->keys[j]>=0){mrb_int nj=(mrb_int)(((mrb_int)h->keys[j])&h->mask);if((j>idx&&(nj<=idx||nj>j))||(j<idx&&nj<=idx&&nj>j)){h->keys[idx]=h->keys[j];h->vals[idx]=h->vals[j];h->keys[j]=-1;h->vals[j]=0;idx=j;}j=(j+1)&h->mask;}return;}idx=(idx+1)&h->mask;}}

static mrb_regexp_pattern *sp_re_pat_0;
static mrb_regexp_pattern *sp_re_pat_1;
static mrb_regexp_pattern *sp_re_pat_2;
static mrb_regexp_pattern *sp_re_pat_3;
static mrb_regexp_pattern *sp_re_pat_4;
static mrb_regexp_pattern *sp_re_pat_5;

static void sp_re_init(void) {
  sp_re_pat_0 = re_compile("\\b", 2, 0);
  sp_re_pat_1 = re_compile("\\A[[:punct:]]+\\z", 16, 0);
  sp_re_pat_2 = re_compile("\\A[[:punct:]]+|[[:punct:]]+\\z", 29, 0);
  sp_re_pat_3 = re_compile("\\Ablock_(\\d+)_(w_o|w_ff1|w_ff2)\\z", 33, 0);
  sp_re_pat_4 = re_compile("\\Ablock_(\\d+)_(w_q|w_k|w_v)_(\\d+)\\z", 35, 0);
  sp_re_pat_5 = re_compile("\\Ablock_(\\d+)_(norm1_gamma|norm2_gamma)\\z", 41, 0);
}

typedef struct sp_TransformerLM_s sp_TransformerLM;

struct sp_TransformerLM_s {
  mrb_int iv_token_embed;
  mrb_int iv_pos_embed;
  sp_IntArray * iv_blocks;
  sp_RbVal iv_norm_final_gamma;
  mrb_int iv_lm_head;
  sp_SymPolyHash * iv_m_state;
  sp_SymPolyHash * iv_v_state;
  mrb_int iv_adam_t;
  sp_SymPolyHash * iv_cache;
  mrb_int iv_vocabulary;
  mrb_int iv_word_to_index;
};

typedef struct { mrb_int _0; mrb_int _1; mrb_int _2; mrb_int _3; } sp_Tuple_int_int_int_int;
static void sp_TransformerLM_gc_scan(void *p) {
  sp_TransformerLM *self = (sp_TransformerLM *)p;
  if (self->iv_blocks) sp_gc_mark((void *)self->iv_blocks);
  if (self->iv_m_state) sp_gc_mark((void *)self->iv_m_state);
  if (self->iv_v_state) sp_gc_mark((void *)self->iv_v_state);
  if (self->iv_cache) sp_gc_mark((void *)self->iv_cache);
}

static sp_TransformerLM *sp_TransformerLM_new(mrb_int lv_vocab_size, mrb_int lv_d_model, mrb_int lv_d_ff, mrb_int lv_n_heads, mrb_int lv_context_length, mrb_int lv_n_layers, mrb_int lv_vocabulary, mrb_int lv_word_to_index);
static inline void sp_TransformerLM_initialize(sp_TransformerLM *self, mrb_int lv_vocab_size, mrb_int lv_d_model, mrb_int lv_d_ff, mrb_int lv_n_heads, mrb_int lv_context_length, mrb_int lv_n_layers, mrb_int lv_vocabulary, mrb_int lv_word_to_index);
static inline mrb_int sp_TransformerLM_init_adam_state(sp_TransformerLM *self);
static inline sp_IntArray * sp_TransformerLM_text_to_token_ids(sp_TransformerLM *self, mrb_int lv_text);
static mrb_int sp_TransformerLM_forward(sp_TransformerLM *self, mrb_int lv_token_ids);
static inline sp_IntArray * sp_TransformerLM_embed(sp_TransformerLM *self, sp_IntArray * lv_token_ids, mrb_int lv_start_pos);
static sp_PolyArray * sp_TransformerLM_transformer_block(sp_TransformerLM *self, sp_RbVal lv_x, mrb_int lv_block);
static sp_PolyArray * sp_TransformerLM_rms_norm(sp_TransformerLM *self, sp_IntArray * lv_x, sp_IntArray * lv_gamma, mrb_float lv_eps);
static sp_PolyArray * sp_TransformerLM_self_attention(sp_TransformerLM *self, mrb_int lv_h_in, mrb_int lv_block);
static inline mrb_int sp_TransformerLM_apply_causal_mask_bang(sp_TransformerLM *self, mrb_int lv_scores, mrb_int lv_query_offset);
static sp_PolyArray * sp_TransformerLM_feed_forward(sp_TransformerLM *self, mrb_int lv_h, mrb_int lv_block);
static sp_SymPolyHash * sp_TransformerLM_backward(sp_TransformerLM *self, mrb_int lv_token_ids);
static sp_PolyArray * sp_TransformerLM_cross_entropy_grad(sp_TransformerLM *self, sp_RbVal lv_logits, mrb_int lv_token_ids, mrb_int lv_n_pred);
static sp_IntArray * sp_TransformerLM_transformer_block_backward(sp_TransformerLM *self, mrb_int lv_dx_out, sp_RbVal lv_x_in, mrb_int lv_block, mrb_int lv_cache);
static sp_PolyArray * sp_TransformerLM_feed_forward_backward(sp_TransformerLM *self, mrb_int lv_d_ff_out, mrb_int lv_h, mrb_int lv_ff_cache, mrb_int lv_block);
static sp_PolyArray * sp_TransformerLM_self_attention_backward(sp_TransformerLM *self, mrb_int lv_d_proj, mrb_int lv_h_in, mrb_int lv_attn_cache, mrb_int lv_block);
static inline mrb_int sp_TransformerLM_softmax_rows_backward(sp_TransformerLM *self, mrb_int lv_softmax_out, mrb_int lv_d_softmax);
static sp_PolyArray * sp_TransformerLM_rms_norm_backward(sp_TransformerLM *self, sp_RbVal lv_x, sp_IntArray * lv_gamma, sp_RbVal lv_rms, mrb_int lv_dy);
static sp_IntArray * sp_TransformerLM_embed_backward(sp_TransformerLM *self, mrb_int lv_token_ids, mrb_int lv_dx);
static inline sp_IntArray * sp_TransformerLM_matrices_of(sp_TransformerLM *self, sp_SymPolyHash * lv_s);
static inline sp_IntArray * sp_TransformerLM_vectors_of(sp_TransformerLM *self, sp_SymPolyHash * lv_s);
static inline sp_SymPolyHash * sp_TransformerLM_model_struct(sp_TransformerLM *self);
static inline sp_SymPolyHash * sp_TransformerLM_zero_gradients(sp_TransformerLM *self);
static inline mrb_int sp_TransformerLM_accumulate_bang(sp_TransformerLM *self, sp_SymPolyHash * lv_acc, sp_SymPolyHash * lv_grads);
static inline mrb_int sp_TransformerLM_scale_gradients_bang(sp_TransformerLM *self, sp_SymPolyHash * lv_acc, mrb_float lv_s);
static sp_PtrArray * sp_TransformerLM_apply_gradients(sp_TransformerLM *self, sp_SymPolyHash * lv_grads, mrb_int lv_lr, mrb_float lv_beta1, mrb_float lv_beta2, mrb_float lv_eps);
static mrb_int sp_TransformerLM_train(sp_TransformerLM *self, mrb_int lv_sequences, mrb_int lv_epochs, mrb_int lv_learning_rate, mrb_int lv_batch_size);
static const char * sp_TransformerLM_generate(sp_TransformerLM *self, mrb_int lv_prompt, mrb_int lv_max_tokens, mrb_float lv_temperature);
static inline sp_SymPolyHash * sp_TransformerLM_empty_kv_cache(sp_TransformerLM *self);
static mrb_int sp_TransformerLM_forward_with_cache(sp_TransformerLM *self, sp_IntArray * lv_new_tokens, sp_SymPolyHash * lv_cache);
static mrb_int sp_TransformerLM_sample_token(sp_TransformerLM *self, mrb_int lv_logits_row, mrb_float lv_temperature);
static inline mrb_int sp_TransformerLM_save_to_file(sp_TransformerLM *self, mrb_int lv_filename);
static inline sp_IntArray * sp_TransformerLM_named_matrices(sp_TransformerLM *self);
static inline sp_IntArray * sp_TransformerLM_named_vectors(sp_TransformerLM *self);
static inline mrb_int sp_TransformerLM_set_named_matrix(sp_TransformerLM *self, mrb_int lv_name, mrb_int lv_matrix);
static mrb_int sp_TransformerLM_set_named_vector(sp_TransformerLM *self, mrb_int lv_name, mrb_int lv_vec);
static inline sp_SymPolyHash * sp_TransformerLM_model_size(sp_TransformerLM *self);
static inline mrb_int sp_TransformerLM_add_vec_bang(sp_TransformerLM *self, mrb_int lv_a, mrb_int lv_b);
static inline mrb_int sp_TransformerLM_scale_vec_bang(sp_TransformerLM *self, mrb_int lv_a, mrb_float lv_s);
static inline mrb_int sp_TransformerLM_adam_step_bang(sp_TransformerLM *self, mrb_int lv_param, mrb_int lv_grad, mrb_int lv_m, mrb_int lv_v, mrb_int lv_lr, mrb_float lv_b1, mrb_float lv_b2, mrb_float lv_eps, mrb_float lv_bc1, mrb_float lv_bc2);
static inline mrb_int sp_TransformerLM_adam_step_vec_bang(sp_TransformerLM *self, mrb_int lv_param, mrb_int lv_grad, mrb_int lv_m, mrb_int lv_v, mrb_int lv_lr, mrb_float lv_b1, mrb_float lv_b2, mrb_float lv_eps, mrb_float lv_bc1, mrb_float lv_bc2);
static sp_IntArray * sp_TransformerLM_cls_create_from_data(mrb_int lv_data, mrb_int lv_d_model, mrb_int lv_d_ff, mrb_int lv_n_heads, mrb_int lv_context_length, mrb_int lv_n_layers);
static mrb_int sp_TransformerLM_cls_load_from_file(mrb_int lv_filename);

static sp_StrArray * cst_CORPUS = NULL;

static inline sp_TransformerLM *sp_TransformerLM_new(mrb_int lv_vocab_size, mrb_int lv_d_model, mrb_int lv_d_ff, mrb_int lv_n_heads, mrb_int lv_context_length, mrb_int lv_n_layers, mrb_int lv_vocabulary, mrb_int lv_word_to_index) {
  SP_GC_SAVE();
  sp_TransformerLM *self = (sp_TransformerLM *)sp_gc_alloc(sizeof(sp_TransformerLM), NULL, sp_TransformerLM_gc_scan);
  SP_GC_ROOT(self);
  mrb_float lv_s = 0.0;
  if (!(((sp_imod(lv_d_model, lv_n_heads)) == 0))) {
    sp_raise(sp_sprintf("d_model (%lld) must divide by n_heads (%lld)", (long long)lv_d_model, (long long)lv_n_heads));
  }
  mrb_int _t1 = lv_vocab_size;
  mrb_int _t2 = lv_d_model;
  mrb_int _t3 = lv_d_ff;
  self->iv_vocab_size = _t1;
  self->iv_d_model = _t2;
  self->iv_d_ff = _t3;
  mrb_int _t4 = lv_n_heads;
  mrb_int _t5 = sp_idiv(lv_d_model, lv_n_heads);
  self->iv_n_heads = _t4;
  self->iv_d_head = _t5;
  mrb_int _t6 = lv_context_length;
  mrb_int _t7 = lv_n_layers;
  self->iv_context_length = _t6;
  self->iv_n_layers = _t7;
  mrb_int _t8 = lv_vocabulary;
  mrb_int _t9 = lv_word_to_index;
  self->iv_vocabulary = _t8;
  self->iv_word_to_index = _t9;
  lv_s = (1.0 / sqrt(lv_d_model));
  self->iv_token_embed = 0;
  self->iv_pos_embed = 0;
  sp_IntArray *_t10 = sp_IntArray_new();
  SP_GC_ROOT(_t10);
  for (mrb_int _t11 = 0; _t11 < lv_n_layers; _t11++) {
    sp_SymPolyHash *_t12 = sp_SymPolyHash_new();
    sp_FloatArray *_t13 = sp_FloatArray_new();
    { mrb_int _n = lv_d_model; mrb_float _v = 1.0; for (mrb_int _i = 0; _i < _n; _i++) sp_FloatArray_push(_t13, _v); }
    sp_SymPolyHash_set(_t12, SPS_norm1_gamma, sp_box_int(_t13));
    sp_IntArray *_t14 = sp_IntArray_new();
    SP_GC_ROOT(_t14);
    for (mrb_int _t15 = 0; _t15 < lv_n_heads; _t15++) {
      sp_IntArray_push(_t14, 0);
    }
    sp_SymPolyHash_set(_t12, SPS_w_q, sp_box_int(_t14));
    sp_IntArray *_t16 = sp_IntArray_new();
    SP_GC_ROOT(_t16);
    for (mrb_int _t17 = 0; _t17 < lv_n_heads; _t17++) {
      sp_IntArray_push(_t16, 0);
    }
    sp_SymPolyHash_set(_t12, SPS_w_k, sp_box_int(_t16));
    sp_IntArray *_t18 = sp_IntArray_new();
    SP_GC_ROOT(_t18);
    for (mrb_int _t19 = 0; _t19 < lv_n_heads; _t19++) {
      sp_IntArray_push(_t18, 0);
    }
    sp_SymPolyHash_set(_t12, SPS_w_v, sp_box_int(_t18));
    sp_SymPolyHash_set(_t12, SPS_w_o, sp_box_int(0));
    sp_FloatArray *_t20 = sp_FloatArray_new();
    { mrb_int _n = lv_d_model; mrb_float _v = 1.0; for (mrb_int _i = 0; _i < _n; _i++) sp_FloatArray_push(_t20, _v); }
    sp_SymPolyHash_set(_t12, SPS_norm2_gamma, sp_box_int(_t20));
    sp_SymPolyHash_set(_t12, SPS_w_ff1, sp_box_int(0));
    sp_SymPolyHash_set(_t12, SPS_w_ff2, sp_box_int(0));
    sp_IntArray_push(_t10, _t12);
  }
  self->iv_blocks = _t10;
  sp_FloatArray *_t21 = sp_FloatArray_new();
  { mrb_int _n = lv_d_model; mrb_float _v = 1.0; for (mrb_int _i = 0; _i < _n; _i++) sp_FloatArray_push(_t21, _v); }
  self->iv_norm_final_gamma = _t21;
  self->iv_lm_head = 0;
  sp_TransformerLM_init_adam_state(self);
  SP_GC_RESTORE();
  return self;
}

static inline void sp_TransformerLM_initialize(sp_TransformerLM *self, mrb_int lv_vocab_size, mrb_int lv_d_model, mrb_int lv_d_ff, mrb_int lv_n_heads, mrb_int lv_context_length, mrb_int lv_n_layers, mrb_int lv_vocabulary, mrb_int lv_word_to_index) {
  mrb_float lv_s = 0.0;
  if (!(((sp_imod(lv_d_model, lv_n_heads)) == 0))) {
    sp_raise(sp_sprintf("d_model (%lld) must divide by n_heads (%lld)", (long long)lv_d_model, (long long)lv_n_heads));
  }
  mrb_int _t22 = lv_vocab_size;
  mrb_int _t23 = lv_d_model;
  mrb_int _t24 = lv_d_ff;
  self->iv_vocab_size = _t22;
  self->iv_d_model = _t23;
  self->iv_d_ff = _t24;
  mrb_int _t25 = lv_n_heads;
  mrb_int _t26 = sp_idiv(lv_d_model, lv_n_heads);
  self->iv_n_heads = _t25;
  self->iv_d_head = _t26;
  mrb_int _t27 = lv_context_length;
  mrb_int _t28 = lv_n_layers;
  self->iv_context_length = _t27;
  self->iv_n_layers = _t28;
  mrb_int _t29 = lv_vocabulary;
  mrb_int _t30 = lv_word_to_index;
  self->iv_vocabulary = _t29;
  self->iv_word_to_index = _t30;
  lv_s = (1.0 / sqrt(lv_d_model));
  self->iv_token_embed = 0;
  self->iv_pos_embed = 0;
  sp_IntArray *_t31 = sp_IntArray_new();
  SP_GC_ROOT(_t31);
  for (mrb_int _t32 = 0; _t32 < lv_n_layers; _t32++) {
    sp_SymPolyHash *_t33 = sp_SymPolyHash_new();
    sp_FloatArray *_t34 = sp_FloatArray_new();
    { mrb_int _n = lv_d_model; mrb_float _v = 1.0; for (mrb_int _i = 0; _i < _n; _i++) sp_FloatArray_push(_t34, _v); }
    sp_SymPolyHash_set(_t33, SPS_norm1_gamma, sp_box_int(_t34));
    sp_IntArray *_t35 = sp_IntArray_new();
    SP_GC_ROOT(_t35);
    for (mrb_int _t36 = 0; _t36 < lv_n_heads; _t36++) {
      sp_IntArray_push(_t35, 0);
    }
    sp_SymPolyHash_set(_t33, SPS_w_q, sp_box_int(_t35));
    sp_IntArray *_t37 = sp_IntArray_new();
    SP_GC_ROOT(_t37);
    for (mrb_int _t38 = 0; _t38 < lv_n_heads; _t38++) {
      sp_IntArray_push(_t37, 0);
    }
    sp_SymPolyHash_set(_t33, SPS_w_k, sp_box_int(_t37));
    sp_IntArray *_t39 = sp_IntArray_new();
    SP_GC_ROOT(_t39);
    for (mrb_int _t40 = 0; _t40 < lv_n_heads; _t40++) {
      sp_IntArray_push(_t39, 0);
    }
    sp_SymPolyHash_set(_t33, SPS_w_v, sp_box_int(_t39));
    sp_SymPolyHash_set(_t33, SPS_w_o, sp_box_int(0));
    sp_FloatArray *_t41 = sp_FloatArray_new();
    { mrb_int _n = lv_d_model; mrb_float _v = 1.0; for (mrb_int _i = 0; _i < _n; _i++) sp_FloatArray_push(_t41, _v); }
    sp_SymPolyHash_set(_t33, SPS_norm2_gamma, sp_box_int(_t41));
    sp_SymPolyHash_set(_t33, SPS_w_ff1, sp_box_int(0));
    sp_SymPolyHash_set(_t33, SPS_w_ff2, sp_box_int(0));
    sp_IntArray_push(_t31, _t33);
  }
  self->iv_blocks = _t31;
  sp_FloatArray *_t42 = sp_FloatArray_new();
  { mrb_int _n = lv_d_model; mrb_float _v = 1.0; for (mrb_int _i = 0; _i < _n; _i++) sp_FloatArray_push(_t42, _v); }
  self->iv_norm_final_gamma = _t42;
  self->iv_lm_head = 0;
  sp_TransformerLM_init_adam_state(self);
}

static inline mrb_int sp_TransformerLM_init_adam_state(sp_TransformerLM *self) {
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    self->iv_m_state = sp_TransformerLM_zero_gradients(self);
    self->iv_v_state = sp_TransformerLM_zero_gradients(self);
    self->iv_adam_t = 0;
    return 0;
  return 0;
}

static inline sp_IntArray * sp_TransformerLM_text_to_token_ids(sp_TransformerLM *self, mrb_int lv_text) {
    mrb_int lv_w = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    mrb_int _t43 = 0;
    sp_IntArray * _t46 = 0;
    SP_GC_ROOT(_t46);
    return sp_IntArray_dup(_t46);
  return NULL;
}

static mrb_int sp_TransformerLM_forward(sp_TransformerLM *self, mrb_int lv_token_ids) {
    SP_GC_SAVE();
    sp_IntArray * lv_x = NULL;
    mrb_int lv_block = 0;
    mrb_int lv_i = 0;
    sp_RbVal lv_x_in = sp_box_nil();
    mrb_int lv_layer_cache = 0;
    mrb_int lv_x_normed = 0;
    mrb_int lv_rms_final = 0;
    mrb_int lv_logits = 0;
    SP_GC_ROOT(lv_x);
    SP_GC_ROOT(self);
    if ((0 > self->iv_context_length)) {
      sp_raise((&("\xff" "context overflow")[1]));
    }
    sp_SymPolyHash *_t47 = sp_SymPolyHash_new();
    sp_SymPolyHash_set(_t47, SPS_token_ids, sp_box_int(lv_token_ids));
    sp_SymPolyHash_set(_t47, SPS_blocks, sp_box_int(sp_IntArray_new()));
    self->iv_cache = _t47;
    lv_x = sp_TransformerLM_embed(self, lv_token_ids, 0);
    sp_SymPolyHash_set(self->iv_cache, SPS_x_embed, sp_box_int(lv_x));
    for (mrb_int _t48 = 0; _t48 < sp_IntArray_length(self->iv_blocks); _t48++) {
      lv_block = sp_IntArray_get(self->iv_blocks, _t48);
      lv_i = _t48;
      const char *_t49 = "";
      if (sp_SymPolyHash_get((sp_SymPolyHash *)(self->iv_cache), SPS_blocks).tag == SP_TAG_OBJ) {
      }
      lv_x_in = (((lv_i) == 0) ? sp_SymPolyHash_get((sp_SymPolyHash *)(self->iv_cache), SPS_x_embed) : 0);
      sp_IntArray *_t50 = sp_TransformerLM_transformer_block(self, lv_x_in, lv_block);
      SP_GC_ROOT(_t50);
      lv_x = sp_IntArray_get(_t50, 0);
      lv_layer_cache = sp_IntArray_get(_t50, 1);
      (sp_SymPolyHash_get((sp_SymPolyHash *)(self->iv_cache), SPS_blocks) << lv_layer_cache);
    }
    sp_IntArray *_t51 = sp_TransformerLM_rms_norm(self, lv_x, self->iv_norm_final_gamma);
    SP_GC_ROOT(_t51);
    lv_x_normed = sp_IntArray_get(_t51, 0);
    lv_rms_final = sp_IntArray_get(_t51, 1);
    sp_SymPolyHash_set(self->iv_cache, SPS_x_block_out, sp_box_int(lv_x));
    sp_SymPolyHash_set(self->iv_cache, SPS_x_final, sp_box_int(lv_x_normed));
    sp_SymPolyHash_set(self->iv_cache, SPS_rms_final, sp_box_int(lv_rms_final));
    lv_logits = 0;
    sp_SymPolyHash_set(self->iv_cache, SPS_logits, sp_box_int(lv_logits));
    return lv_logits;
  return 0;
}

static inline sp_IntArray * sp_TransformerLM_embed(sp_TransformerLM *self, sp_IntArray * lv_token_ids, mrb_int lv_start_pos) {
    mrb_int lv_i = 0;
    mrb_int lv_tok = 0;
    mrb_int lv_pos = 0;
    mrb_int lv_j = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    SP_GC_ROOT(lv_token_ids);
    sp_IntArray *_t52 = sp_IntArray_new();
    SP_GC_ROOT(_t52);
    for (mrb_int _t53 = 0; _t53 < sp_IntArray_length(lv_token_ids); _t53++) {
      lv_i = _t53;
      lv_tok = 0;
      lv_pos = 0;
      sp_IntArray *_t54 = sp_IntArray_new();
      SP_GC_ROOT(_t54);
      for (mrb_int _t55 = 0; _t55 < self->iv_d_model; _t55++) {
        lv_j = _t55;
        sp_IntArray_push(_t54, (0 + 0));
      }
      sp_IntArray_push(_t52, _t54);
    }
    _t52;
    return NULL;
  return NULL;
}

static sp_PolyArray * sp_TransformerLM_transformer_block(sp_TransformerLM *self, sp_RbVal lv_x, mrb_int lv_block) {
    SP_GC_SAVE();
    sp_StrIntHash * lv_cache = NULL;
    mrb_int lv_h = 0;
    mrb_int lv_rms1 = 0;
    mrb_int lv_attn_proj = 0;
    mrb_int lv_attn_cache = 0;
    mrb_int lv_x_attn = 0;
    mrb_int lv_h2 = 0;
    mrb_int lv_rms2 = 0;
    mrb_int lv_ff_out = 0;
    mrb_int lv_ff_cache = 0;
    mrb_int lv_x_out = 0;
    SP_GC_ROOT(lv_cache);
    SP_GC_ROOT(self);
    lv_cache = sp_StrIntHash_new();
    sp_IntArray *_t56 = sp_TransformerLM_rms_norm(self, lv_x, 0);
    SP_GC_ROOT(_t56);
    lv_h = sp_IntArray_get(_t56, 0);
    lv_rms1 = sp_IntArray_get(_t56, 1);
    sp_IntArray *_t57 = sp_TransformerLM_self_attention(self, lv_h, lv_block);
    SP_GC_ROOT(_t57);
    lv_attn_proj = sp_IntArray_get(_t57, 0);
    lv_attn_cache = sp_IntArray_get(_t57, 1);
    lv_x_attn = 0;
    sp_StrIntHash_update(lv_cache, 0);
    sp_IntArray *_t58 = sp_TransformerLM_rms_norm(self, lv_x_attn, 0);
    SP_GC_ROOT(_t58);
    lv_h2 = sp_IntArray_get(_t58, 0);
    lv_rms2 = sp_IntArray_get(_t58, 1);
    sp_IntArray *_t59 = sp_TransformerLM_feed_forward(self, lv_h2, lv_block);
    SP_GC_ROOT(_t59);
    lv_ff_out = sp_IntArray_get(_t59, 0);
    lv_ff_cache = sp_IntArray_get(_t59, 1);
    lv_x_out = 0;
    sp_StrIntHash_update(lv_cache, 0);
    sp_PolyArray *_t60 = sp_PolyArray_new();
    sp_PolyArray_push(_t60, sp_box_int(lv_x_out));
    sp_PolyArray_push(_t60, sp_box_int(lv_cache));
    return _t60;
  return 0;
}

static sp_PolyArray * sp_TransformerLM_rms_norm(sp_TransformerLM *self, sp_IntArray * lv_x, sp_IntArray * lv_gamma, mrb_float lv_eps) {
    SP_GC_SAVE();
    mrb_int lv_d = 0;
    sp_FloatArray * lv_rms = NULL;
    mrb_int lv_row = 0;
    mrb_int lv_v = 0;
    mrb_int lv_y = 0;
    mrb_int lv_i = 0;
    mrb_float lv_r = 0.0;
    mrb_int lv_j = 0;
    SP_GC_ROOT(lv_rms);
    SP_GC_ROOT(self);
    SP_GC_ROOT(lv_x);
    SP_GC_ROOT(lv_gamma);
    lv_d = sp_IntArray_length(lv_gamma);
    sp_IntArray * _t61 = lv_x;
    sp_IntArray *_t62 = sp_IntArray_new();
    for (mrb_int _t63 = 0; _t63 < sp_IntArray_length(_t61); _t63++) {
      lv_row = sp_IntArray_get(_t61, _t63);
      mrb_int _t64 = 0;
      for (mrb_int _t65 = 0; _t65 < sp_IntArray_length(lv_row); _t65++) {
        lv_v = sp_IntArray_get(lv_row, _t65);
        _t64 += (lv_v * lv_v);
      }
      sp_IntArray_push(_t62, sqrt((sp_idiv(_t64, lv_d) + lv_eps)));
    }
    lv_rms = _t62;
    mrb_int _t66 = 0;
    lv_y = 0;
    sp_PolyArray *_t69 = sp_PolyArray_new();
    sp_PolyArray_push(_t69, sp_box_int(lv_y));
    sp_PolyArray_push(_t69, sp_box_int(lv_rms));
    return _t69;
  return 0;
}

static sp_PolyArray * sp_TransformerLM_self_attention(sp_TransformerLM *self, mrb_int lv_h_in, mrb_int lv_block) {
    SP_GC_SAVE();
    mrb_float lv_inv_sqrt = 0.0;
    sp_IntArray * lv_per_head = NULL;
    mrb_int lv_head_idx = 0;
    mrb_int lv_q = 0;
    mrb_int lv_k = 0;
    mrb_int lv_v = 0;
    mrb_int lv_scores = 0;
    mrb_int lv_attn = 0;
    mrb_int lv_out = 0;
    mrb_int lv_concat = 0;
    mrb_int lv_head = 0;
    mrb_int lv_proj = 0;
    SP_GC_ROOT(lv_per_head);
    SP_GC_ROOT(self);
    lv_inv_sqrt = (1.0 / sqrt(self->iv_d_head));
    sp_IntArray *_t70 = sp_IntArray_new();
    SP_GC_ROOT(_t70);
    for (mrb_int _t71 = 0; _t71 < self->iv_n_heads; _t71++) {
      lv_head_idx = _t71;
      lv_q = 0;
      lv_k = 0;
      lv_v = 0;
      lv_scores = 0;
      sp_TransformerLM_apply_causal_mask_bang(self, lv_scores, 0);
      lv_attn = 0;
      lv_out = 0;
      sp_SymIntHash *_t72 = sp_SymIntHash_new();
      sp_SymIntHash_set(_t72, SPS_q, lv_q);
      sp_SymIntHash_set(_t72, SPS_k, lv_k);
      sp_SymIntHash_set(_t72, SPS_v, lv_v);
      sp_SymIntHash_set(_t72, SPS_attn, lv_attn);
      sp_SymIntHash_set(_t72, SPS_out, lv_out);
      sp_IntArray_push(_t70, _t72);
    }
    lv_per_head = _t70;
    lv_concat = 0;
    lv_proj = 0;
    sp_PolyArray *_t73 = sp_PolyArray_new();
    sp_PolyArray_push(_t73, sp_box_int(lv_proj));
    sp_SymPolyHash *_t74 = sp_SymPolyHash_new();
    sp_SymPolyHash_set(_t74, SPS_per_head, sp_box_int(lv_per_head));
    sp_SymPolyHash_set(_t74, SPS_concat, sp_box_int(lv_concat));
    sp_PolyArray_push(_t73, sp_box_int(_t74));
    return _t73;
  return 0;
}

static inline mrb_int sp_TransformerLM_apply_causal_mask_bang(sp_TransformerLM *self, mrb_int lv_scores, mrb_int lv_query_offset) {
    mrb_int lv_row = 0;
    mrb_int lv_i = 0;
    mrb_int lv_first_masked = 0;
    mrb_int lv_j = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    for (mrb_int _t75 = 0; _t75 < sp_IntArray_length(lv_scores); _t75++) {
      lv_row = sp_IntArray_get(lv_scores, _t75);
      lv_i = _t75;
      lv_first_masked = ((lv_query_offset + lv_i) + 1);
      sp_Range _t77 = sp_range_new(lv_first_masked, 0);
      for (lv_j = _t77.first; lv_j <= _t77.last; lv_j++) {
      }
    }
    return 0;
  return 0;
}

static sp_PolyArray * sp_TransformerLM_feed_forward(sp_TransformerLM *self, mrb_int lv_h, mrb_int lv_block) {
    mrb_int lv_pre = 0;
    mrb_int lv_hidden = 0;
    mrb_int lv_row = 0;
    mrb_int lv_v = 0;
    mrb_int lv_out = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    lv_pre = 0;
    mrb_int _t78 = lv_pre;
    lv_hidden = 0;
    lv_out = 0;
    sp_PolyArray *_t81 = sp_PolyArray_new();
    sp_PolyArray_push(_t81, sp_box_int(lv_out));
    sp_SymIntHash *_t82 = sp_SymIntHash_new();
    sp_SymIntHash_set(_t82, SPS_pre, lv_pre);
    sp_SymIntHash_set(_t82, SPS_hidden, lv_hidden);
    sp_PolyArray_push(_t81, sp_box_int(_t82));
    return _t81;
  return 0;
}

static sp_SymPolyHash * sp_TransformerLM_backward(sp_TransformerLM *self, mrb_int lv_token_ids) {
    SP_GC_SAVE();
    mrb_int lv_n_pred = 0;
    mrb_int lv_dlogits = 0;
    mrb_int lv_total_loss = 0;
    mrb_int lv_grad_lm_head = 0;
    mrb_int lv_dx_final = 0;
    mrb_int lv_dx = 0;
    mrb_int lv_grad_norm_final = 0;
    sp_IntArray * lv_grad_blocks = NULL;
    mrb_int lv_block = 0;
    mrb_int lv_i = 0;
    sp_RbVal lv_x_in = sp_box_nil();
    mrb_int lv_grad_token_embed = 0;
    mrb_int lv_grad_pos_embed = 0;
    SP_GC_ROOT(lv_grad_blocks);
    SP_GC_ROOT(self);
    lv_n_pred = (0 - 1);
    if ((lv_n_pred <= 0)) {
      sp_SymPolyHash * _t83 = sp_TransformerLM_zero_gradients(self);
      SP_GC_RESTORE();
      return _t83;
    }
    sp_IntArray *_t84 = sp_TransformerLM_cross_entropy_grad(self, sp_SymPolyHash_get((sp_SymPolyHash *)(self->iv_cache), SPS_logits), lv_token_ids, lv_n_pred);
    SP_GC_ROOT(_t84);
    lv_dlogits = sp_IntArray_get(_t84, 0);
    lv_total_loss = sp_IntArray_get(_t84, 1);
    lv_grad_lm_head = 0;
    lv_dx_final = 0;
    sp_RbVal _t86 = sp_SymPolyHash_get((sp_SymPolyHash *)(self->iv_cache), SPS_x_block_out);
    sp_RbVal _t87 = sp_SymPolyHash_get((sp_SymPolyHash *)(self->iv_cache), SPS_rms_final);
    sp_IntArray *_t85 = sp_TransformerLM_rms_norm_backward(self, _t86, self->iv_norm_final_gamma, _t87, lv_dx_final);
    SP_GC_ROOT(_t85);
    lv_dx = sp_IntArray_get(_t85, 0);
    lv_grad_norm_final = sp_IntArray_get(_t85, 1);
    lv_grad_blocks = sp_IntArray_new();
    sp_IntArray * _t88 = 0;
    SP_GC_ROOT(_t88);
    sp_IntArray *_t89 = sp_TransformerLM_embed_backward(self, lv_token_ids, lv_dx);
    SP_GC_ROOT(_t89);
    lv_grad_token_embed = sp_IntArray_get(_t89, 0);
    lv_grad_pos_embed = sp_IntArray_get(_t89, 1);
    sp_SymPolyHash *_t90 = sp_SymPolyHash_new();
    sp_SymPolyHash_set(_t90, SPS_token_embed, sp_box_int(lv_grad_token_embed));
    sp_SymPolyHash_set(_t90, SPS_pos_embed, sp_box_int(lv_grad_pos_embed));
    sp_SymPolyHash_set(_t90, SPS_lm_head, sp_box_int(lv_grad_lm_head));
    sp_SymPolyHash_set(_t90, SPS_norm_final_gamma, sp_box_int(lv_grad_norm_final));
    sp_SymPolyHash_set(_t90, SPS_blocks, sp_box_int(lv_grad_blocks));
    sp_SymPolyHash_set(_t90, SPS_loss, sp_box_int(sp_idiv(lv_total_loss, lv_n_pred)));
    return _t90;
  return NULL;
}

static sp_PolyArray * sp_TransformerLM_cross_entropy_grad(sp_TransformerLM *self, sp_RbVal lv_logits, mrb_int lv_token_ids, mrb_int lv_n_pred) {
    SP_GC_SAVE();
    mrb_int lv_dlogits = 0;
    mrb_float lv_total_loss = 0.0;
    mrb_float lv_inv_n = 0.0;
    mrb_int lv_i = 0;
    mrb_int lv_row = 0;
    mrb_int lv_mx = 0;
    sp_FloatArray * lv_exp = NULL;
    mrb_int lv_v = 0;
    mrb_float lv_sum = 0.0;
    mrb_int lv_target = 0;
    mrb_float lv_e = 0.0;
    mrb_int lv_c = 0;
    SP_GC_ROOT(lv_exp);
    SP_GC_ROOT(self);
    lv_dlogits = 0;
    lv_total_loss = 0.0;
    lv_inv_n = (1.0 / lv_n_pred);
    for (mrb_int _t91 = 0; _t91 < lv_n_pred; _t91++) {
      lv_i = _t91;
      const char *_t92 = "";
      if (lv_logits.tag == SP_TAG_OBJ) {
      }
      lv_row = _t92;
      lv_mx = 0;
      mrb_int _t93 = lv_row;
      lv_exp = 0;
      lv_sum = sp_FloatArray_sum(lv_exp);
      lv_target = 0;
      sp_FloatArray *_t96 = sp_FloatArray_new();
      sp_FloatArray_push(_t96, (sp_FloatArray_get(lv_exp, lv_target) / lv_sum));
      sp_FloatArray_push(_t96, 9.9999999999999998e-13);
      lv_total_loss += (-log(sp_FloatArray_max(_t96)));
      for (mrb_int _t97 = 0; _t97 < sp_FloatArray_length(lv_exp); _t97++) {
        lv_e = sp_FloatArray_get(lv_exp, _t97);
        lv_c = _t97;
      }
    }
    sp_PolyArray *_t98 = sp_PolyArray_new();
    sp_PolyArray_push(_t98, sp_box_int(lv_dlogits));
    sp_PolyArray_push(_t98, sp_box_float(lv_total_loss));
    return _t98;
  return 0;
}

static sp_IntArray * sp_TransformerLM_transformer_block_backward(sp_TransformerLM *self, mrb_int lv_dx_out, sp_RbVal lv_x_in, mrb_int lv_block, mrb_int lv_cache) {
    mrb_int lv_d_h_norm2 = 0;
    mrb_int lv_ffn_grads = 0;
    mrb_int lv_d_x_attn_via_norm = 0;
    mrb_int lv_d_norm2_gamma = 0;
    mrb_int lv_d_x_attn = 0;
    mrb_int lv_d_h_norm1 = 0;
    mrb_int lv_attn_grads = 0;
    mrb_int lv_d_x_in_via_norm = 0;
    mrb_int lv_d_norm1_gamma = 0;
    mrb_int lv_d_x_in = 0;
    mrb_int lv_grads = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    mrb_int _t100 = 0;
    mrb_int _t101 = 0;
    sp_IntArray *_t99 = sp_TransformerLM_feed_forward_backward(self, lv_dx_out, _t100, _t101, lv_block);
    SP_GC_ROOT(_t99);
    lv_d_h_norm2 = sp_IntArray_get(_t99, 0);
    lv_ffn_grads = sp_IntArray_get(_t99, 1);
    mrb_int _t103 = 0;
    mrb_int _t104 = 0;
    mrb_int _t105 = 0;
    sp_IntArray *_t102 = sp_TransformerLM_rms_norm_backward(self, _t103, _t104, _t105, lv_d_h_norm2);
    SP_GC_ROOT(_t102);
    lv_d_x_attn_via_norm = sp_IntArray_get(_t102, 0);
    lv_d_norm2_gamma = sp_IntArray_get(_t102, 1);
    lv_d_x_attn = 0;
    mrb_int _t107 = 0;
    mrb_int _t108 = 0;
    sp_IntArray *_t106 = sp_TransformerLM_self_attention_backward(self, lv_d_x_attn, _t107, _t108, lv_block);
    SP_GC_ROOT(_t106);
    lv_d_h_norm1 = sp_IntArray_get(_t106, 0);
    lv_attn_grads = sp_IntArray_get(_t106, 1);
    mrb_int _t110 = 0;
    mrb_int _t111 = 0;
    sp_IntArray *_t109 = sp_TransformerLM_rms_norm_backward(self, lv_x_in, _t110, _t111, lv_d_h_norm1);
    SP_GC_ROOT(_t109);
    lv_d_x_in_via_norm = sp_IntArray_get(_t109, 0);
    lv_d_norm1_gamma = sp_IntArray_get(_t109, 1);
    lv_d_x_in = 0;
    lv_grads = 0;
    sp_IntArray *_t112 = sp_IntArray_new();
    sp_IntArray_push(_t112, lv_d_x_in);
    sp_IntArray_push(_t112, lv_grads);
    return _t112;
  return NULL;
}

static sp_PolyArray * sp_TransformerLM_feed_forward_backward(sp_TransformerLM *self, mrb_int lv_d_ff_out, mrb_int lv_h, mrb_int lv_ff_cache, mrb_int lv_block) {
    mrb_int lv_d_w_ff2 = 0;
    mrb_int lv_d_hidden = 0;
    mrb_int lv_d_pre = 0;
    mrb_int lv_row = 0;
    mrb_int lv_i = 0;
    mrb_int lv_v = 0;
    mrb_int lv_j = 0;
    mrb_int lv_d_w_ff1 = 0;
    mrb_int lv_d_h = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    lv_d_w_ff2 = 0;
    lv_d_hidden = 0;
    mrb_int _t113 = 0;
    lv_d_pre = 0;
    lv_d_w_ff1 = 0;
    lv_d_h = 0;
    sp_PolyArray *_t116 = sp_PolyArray_new();
    sp_PolyArray_push(_t116, sp_box_int(lv_d_h));
    sp_SymIntHash *_t117 = sp_SymIntHash_new();
    sp_SymIntHash_set(_t117, SPS_w_ff1, lv_d_w_ff1);
    sp_SymIntHash_set(_t117, SPS_w_ff2, lv_d_w_ff2);
    sp_PolyArray_push(_t116, sp_box_int(_t117));
    return _t116;
  return 0;
}

static sp_PolyArray * sp_TransformerLM_self_attention_backward(sp_TransformerLM *self, mrb_int lv_d_proj, mrb_int lv_h_in, mrb_int lv_attn_cache, mrb_int lv_block) {
    SP_GC_SAVE();
    mrb_int lv_d_w_o = 0;
    mrb_int lv_d_concat = 0;
    mrb_int lv_d_outs = 0;
    sp_IntArray * lv_d_w_q_per_head = NULL;
    sp_IntArray * lv_d_w_k_per_head = NULL;
    sp_IntArray * lv_d_w_v_per_head = NULL;
    mrb_int lv_d_h_in = 0;
    mrb_float lv_inv_sqrt = 0.0;
    mrb_int lv_head_idx = 0;
    mrb_int lv_head = 0;
    mrb_int lv_d_out_h = 0;
    mrb_int lv_d_attn = 0;
    mrb_int lv_d_v = 0;
    mrb_int lv_d_scores = 0;
    mrb_int lv_d_q = 0;
    mrb_int lv_d_k = 0;
    SP_GC_ROOT(lv_d_w_q_per_head);
    SP_GC_ROOT(lv_d_w_k_per_head);
    SP_GC_ROOT(lv_d_w_v_per_head);
    SP_GC_ROOT(self);
    lv_d_w_o = 0;
    lv_d_concat = 0;
    lv_d_outs = 0;
    lv_d_w_q_per_head = sp_IntArray_new();
    lv_d_w_k_per_head = sp_IntArray_new();
    lv_d_w_v_per_head = sp_IntArray_new();
    lv_d_h_in = 0;
    lv_inv_sqrt = (1.0 / sqrt(self->iv_d_head));
    for (mrb_int _t118 = 0; _t118 < self->iv_n_heads; _t118++) {
      lv_head_idx = _t118;
      lv_head = 0;
      lv_d_out_h = 0;
      lv_d_attn = 0;
      lv_d_v = 0;
      lv_d_scores = sp_TransformerLM_softmax_rows_backward(self, 0, lv_d_attn);
      lv_d_q = 0;
      lv_d_k = 0;
      sp_IntArray_set(lv_d_w_q_per_head, lv_head_idx, 0);
      sp_IntArray_set(lv_d_w_k_per_head, lv_head_idx, 0);
      sp_IntArray_set(lv_d_w_v_per_head, lv_head_idx, 0);
    }
    sp_PolyArray *_t119 = sp_PolyArray_new();
    sp_PolyArray_push(_t119, sp_box_int(lv_d_h_in));
    sp_SymPolyHash *_t120 = sp_SymPolyHash_new();
    sp_SymPolyHash_set(_t120, SPS_w_q, sp_box_int(lv_d_w_q_per_head));
    sp_SymPolyHash_set(_t120, SPS_w_k, sp_box_int(lv_d_w_k_per_head));
    sp_SymPolyHash_set(_t120, SPS_w_v, sp_box_int(lv_d_w_v_per_head));
    sp_SymPolyHash_set(_t120, SPS_w_o, sp_box_int(lv_d_w_o));
    sp_PolyArray_push(_t119, sp_box_int(_t120));
    return _t119;
  return 0;
}

static inline mrb_int sp_TransformerLM_softmax_rows_backward(sp_TransformerLM *self, mrb_int lv_softmax_out, mrb_int lv_d_softmax) {
    SP_GC_SAVE();
    mrb_int lv_row = 0;
    mrb_int lv_i = 0;
    mrb_int lv_d_row = 0;
    mrb_int lv_s = 0;
    sp_IntArray * lv_p = NULL;
    sp_IntArray * lv_dp = NULL;
    mrb_int lv_j = 0;
    SP_GC_ROOT(lv_p);
    SP_GC_ROOT(lv_dp);
    SP_GC_ROOT(self);
    mrb_int _t121 = 0;
    return 0;
  return 0;
}

static sp_PolyArray * sp_TransformerLM_rms_norm_backward(sp_TransformerLM *self, sp_RbVal lv_x, sp_IntArray * lv_gamma, sp_RbVal lv_rms, mrb_int lv_dy) {
    SP_GC_SAVE();
    mrb_int lv_d = 0;
    sp_IntArray * lv_dx = NULL;
    sp_FloatArray * lv_dgamma = NULL;
    mrb_int lv_row = 0;
    mrb_int lv_i = 0;
    mrb_int lv_r = 0;
    mrb_float lv_inner = 0.0;
    mrb_int lv_j = 0;
    mrb_float lv_coef = 0.0;
    SP_GC_ROOT(lv_dx);
    SP_GC_ROOT(lv_dgamma);
    SP_GC_ROOT(self);
    SP_GC_ROOT(lv_gamma);
    lv_d = sp_IntArray_length(lv_gamma);
    const char *_t124 = "";
    if (lv_x.tag == SP_TAG_OBJ) {
    }
    sp_IntArray *_t125 = sp_IntArray_new();
    SP_GC_ROOT(_t125);
    for (mrb_int _t126 = 0; _t126 < _t124; _t126++) {
      sp_FloatArray *_t127 = sp_FloatArray_new();
      { mrb_int _n = lv_d; mrb_float _v = 0.0; for (mrb_int _i = 0; _i < _n; _i++) sp_FloatArray_push(_t127, _v); }
      sp_IntArray_push(_t125, _t127);
    }
    lv_dx = _t125;
    sp_FloatArray *_t128 = sp_FloatArray_new();
    { mrb_int _n = lv_d; mrb_float _v = 0.0; for (mrb_int _i = 0; _i < _n; _i++) sp_FloatArray_push(_t128, _v); }
    lv_dgamma = _t128;
    for (mrb_int _t129 = 0; _t129 < sp_IntArray_length(lv_x); _t129++) {
      lv_row = sp_IntArray_get(lv_x, _t129);
      lv_i = _t129;
      const char *_t130 = "";
      if (lv_rms.tag == SP_TAG_OBJ) {
      }
      lv_r = _t130;
      lv_inner = 0.0;
      for (mrb_int _t131 = 0; _t131 < lv_d; _t131++) {
        lv_j = _t131;
        lv_inner += ((0 * sp_IntArray_get(lv_gamma, lv_j)) * 0);
      }
      lv_coef = (lv_inner / ((lv_d * lv_r) * lv_r));
      for (mrb_int _t132 = 0; _t132 < lv_d; _t132++) {
        lv_j = _t132;
      }
    }
    sp_PolyArray *_t133 = sp_PolyArray_new();
    sp_PolyArray_push(_t133, sp_box_int(lv_dx));
    sp_PolyArray_push(_t133, sp_box_int(lv_dgamma));
    return _t133;
  return 0;
}

static sp_IntArray * sp_TransformerLM_embed_backward(sp_TransformerLM *self, mrb_int lv_token_ids, mrb_int lv_dx) {
    mrb_int lv_grad_token = 0;
    mrb_int lv_grad_pos = 0;
    mrb_int lv_tok = 0;
    mrb_int lv_i = 0;
    mrb_int lv_j = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    lv_grad_token = 0;
    lv_grad_pos = 0;
    for (mrb_int _t134 = 0; _t134 < sp_IntArray_length(lv_token_ids); _t134++) {
      lv_tok = sp_IntArray_get(lv_token_ids, _t134);
      lv_i = _t134;
      for (mrb_int _t135 = 0; _t135 < self->iv_d_model; _t135++) {
        lv_j = _t135;
      }
    }
    sp_IntArray *_t136 = sp_IntArray_new();
    sp_IntArray_push(_t136, lv_grad_token);
    sp_IntArray_push(_t136, lv_grad_pos);
    return _t136;
  return NULL;
}

static inline sp_IntArray * sp_TransformerLM_matrices_of(sp_TransformerLM *self, sp_SymPolyHash * lv_s) {
    SP_GC_SAVE();
    sp_IntArray * lv_out = NULL;
    mrb_int lv_b = 0;
    mrb_int lv_k = 0;
    mrb_int lv_m = 0;
    SP_GC_ROOT(lv_out);
    SP_GC_ROOT(self);
    SP_GC_ROOT(lv_s);
    sp_IntArray *_t137 = sp_IntArray_new();
    sp_IntArray_push(_t137, sp_SymPolyHash_get((sp_SymPolyHash *)(lv_s), SPS_token_embed));
    sp_IntArray_push(_t137, sp_SymPolyHash_get((sp_SymPolyHash *)(lv_s), SPS_pos_embed));
    sp_IntArray_push(_t137, sp_SymPolyHash_get((sp_SymPolyHash *)(lv_s), SPS_lm_head));
    lv_out = _t137;
    return lv_out;
  return NULL;
}

static inline sp_IntArray * sp_TransformerLM_vectors_of(sp_TransformerLM *self, sp_SymPolyHash * lv_s) {
    SP_GC_SAVE();
    sp_IntArray * lv_out = NULL;
    mrb_int lv_b = 0;
    mrb_int lv_k = 0;
    SP_GC_ROOT(lv_out);
    SP_GC_ROOT(self);
    SP_GC_ROOT(lv_s);
    sp_IntArray *_t138 = sp_IntArray_new();
    sp_IntArray_push(_t138, sp_SymPolyHash_get((sp_SymPolyHash *)(lv_s), SPS_norm_final_gamma));
    lv_out = _t138;
    return lv_out;
  return NULL;
}

static inline sp_SymPolyHash * sp_TransformerLM_model_struct(sp_TransformerLM *self) {
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    sp_SymPolyHash *_t139 = sp_SymPolyHash_new();
    sp_SymPolyHash_set(_t139, SPS_token_embed, sp_box_int(self->iv_token_embed));
    sp_SymPolyHash_set(_t139, SPS_pos_embed, sp_box_int(self->iv_pos_embed));
    sp_SymPolyHash_set(_t139, SPS_lm_head, sp_box_int(self->iv_lm_head));
    sp_SymPolyHash_set(_t139, SPS_norm_final_gamma, self->iv_norm_final_gamma);
    sp_SymPolyHash_set(_t139, SPS_blocks, sp_box_int(self->iv_blocks));
    return _t139;
  return NULL;
}

static inline sp_SymPolyHash * sp_TransformerLM_zero_gradients(sp_TransformerLM *self) {
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    sp_SymPolyHash *_t140 = sp_SymPolyHash_new();
    sp_SymPolyHash_set(_t140, SPS_token_embed, sp_box_int(0));
    sp_SymPolyHash_set(_t140, SPS_pos_embed, sp_box_int(0));
    sp_SymPolyHash_set(_t140, SPS_lm_head, sp_box_int(0));
    sp_FloatArray *_t141 = sp_FloatArray_new();
    { mrb_int _n = self->iv_d_model; mrb_float _v = 0.0; for (mrb_int _i = 0; _i < _n; _i++) sp_FloatArray_push(_t141, _v); }
    sp_SymPolyHash_set(_t140, SPS_norm_final_gamma, sp_box_int(_t141));
    sp_IntArray *_t142 = sp_IntArray_new();
    SP_GC_ROOT(_t142);
    for (mrb_int _t143 = 0; _t143 < self->iv_n_layers; _t143++) {
      sp_SymPolyHash *_t144 = sp_SymPolyHash_new();
      sp_FloatArray *_t145 = sp_FloatArray_new();
      { mrb_int _n = self->iv_d_model; mrb_float _v = 0.0; for (mrb_int _i = 0; _i < _n; _i++) sp_FloatArray_push(_t145, _v); }
      sp_SymPolyHash_set(_t144, SPS_norm1_gamma, sp_box_int(_t145));
      sp_FloatArray *_t146 = sp_FloatArray_new();
      { mrb_int _n = self->iv_d_model; mrb_float _v = 0.0; for (mrb_int _i = 0; _i < _n; _i++) sp_FloatArray_push(_t146, _v); }
      sp_SymPolyHash_set(_t144, SPS_norm2_gamma, sp_box_int(_t146));
      sp_IntArray *_t147 = sp_IntArray_new();
      SP_GC_ROOT(_t147);
      for (mrb_int _t148 = 0; _t148 < self->iv_n_heads; _t148++) {
        sp_IntArray_push(_t147, 0);
      }
      sp_SymPolyHash_set(_t144, SPS_w_q, sp_box_int(_t147));
      sp_IntArray *_t149 = sp_IntArray_new();
      SP_GC_ROOT(_t149);
      for (mrb_int _t150 = 0; _t150 < self->iv_n_heads; _t150++) {
        sp_IntArray_push(_t149, 0);
      }
      sp_SymPolyHash_set(_t144, SPS_w_k, sp_box_int(_t149));
      sp_IntArray *_t151 = sp_IntArray_new();
      SP_GC_ROOT(_t151);
      for (mrb_int _t152 = 0; _t152 < self->iv_n_heads; _t152++) {
        sp_IntArray_push(_t151, 0);
      }
      sp_SymPolyHash_set(_t144, SPS_w_v, sp_box_int(_t151));
      sp_SymPolyHash_set(_t144, SPS_w_o, sp_box_int(0));
      sp_SymPolyHash_set(_t144, SPS_w_ff1, sp_box_int(0));
      sp_SymPolyHash_set(_t144, SPS_w_ff2, sp_box_int(0));
      sp_IntArray_push(_t142, _t144);
    }
    sp_SymPolyHash_set(_t140, SPS_blocks, sp_box_int(_t142));
    sp_SymPolyHash_set(_t140, SPS_loss, sp_box_float(0.0));
    return _t140;
  return NULL;
}

static inline mrb_int sp_TransformerLM_accumulate_bang(sp_TransformerLM *self, sp_SymPolyHash * lv_acc, sp_SymPolyHash * lv_grads) {
    mrb_int lv_a = 0;
    mrb_int lv_g = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    SP_GC_ROOT(lv_acc);
    SP_GC_ROOT(lv_grads);
    sp_IntArray * _t153 = sp_TransformerLM_matrices_of(self, lv_acc);
    SP_GC_ROOT(_t153);
    for (mrb_int _t154 = 0; _t154 < sp_IntArray_length(_t153); _t154++) {
      lv_a = sp_IntArray_get(_t153, _t154);
      lv_g = sp_IntArray_get(sp_TransformerLM_matrices_of(self, lv_grads), _t154);
    }
    sp_IntArray * _t155 = sp_TransformerLM_vectors_of(self, lv_acc);
    SP_GC_ROOT(_t155);
    for (mrb_int _t156 = 0; _t156 < sp_IntArray_length(_t155); _t156++) {
      lv_a = sp_IntArray_get(_t155, _t156);
      lv_g = sp_IntArray_get(sp_TransformerLM_vectors_of(self, lv_grads), _t156);
      sp_TransformerLM_add_vec_bang(self, lv_a, lv_g);
    }
    return 0;
  return 0;
}

static inline mrb_int sp_TransformerLM_scale_gradients_bang(sp_TransformerLM *self, sp_SymPolyHash * lv_acc, mrb_float lv_s) {
    mrb_int lv_m = 0;
    mrb_int lv_v = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    SP_GC_ROOT(lv_acc);
    sp_IntArray * _t157 = sp_TransformerLM_matrices_of(self, lv_acc);
    SP_GC_ROOT(_t157);
    for (mrb_int _t158 = 0; _t158 < sp_IntArray_length(_t157); _t158++) {
      lv_m = sp_IntArray_get(_t157, _t158);
    }
    sp_IntArray * _t159 = sp_TransformerLM_vectors_of(self, lv_acc);
    SP_GC_ROOT(_t159);
    for (mrb_int _t160 = 0; _t160 < sp_IntArray_length(_t159); _t160++) {
      lv_v = sp_IntArray_get(_t159, _t160);
      sp_TransformerLM_scale_vec_bang(self, lv_v, lv_s);
    }
    return 0;
  return 0;
}

static sp_PtrArray * sp_TransformerLM_apply_gradients(sp_TransformerLM *self, sp_SymPolyHash * lv_grads, mrb_int lv_lr, mrb_float lv_beta1, mrb_float lv_beta2, mrb_float lv_eps) {
    mrb_float lv_bc1 = 0.0;
    mrb_float lv_bc2 = 0.0;
    mrb_int lv_p = 0;
    mrb_int lv_g = 0;
    mrb_int lv_m = 0;
    mrb_int lv_v = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    SP_GC_ROOT(lv_grads);
    self->iv_adam_t += 1;
    lv_bc1 = (1.0 - pow(lv_beta1, self->iv_adam_t));
    lv_bc2 = (1.0 - pow(lv_beta2, self->iv_adam_t));
    sp_IntArray * _t161 = sp_TransformerLM_matrices_of(self, sp_TransformerLM_model_struct(self));
    SP_GC_ROOT(_t161);
    for (mrb_int _t162 = 0; _t162 < sp_IntArray_length(_t161); _t162++) {
      lv_p = sp_IntArray_get(_t161, _t162);
      lv_g = sp_IntArray_get(sp_TransformerLM_matrices_of(self, lv_grads), _t162);
      sp_TransformerLM_adam_step_bang(self, lv_p, lv_g, lv_m, lv_v, lv_lr, lv_beta1, lv_beta2, lv_eps, lv_bc1, lv_bc2);
    }
    sp_IntArray * _t163 = sp_TransformerLM_vectors_of(self, sp_TransformerLM_model_struct(self));
    SP_GC_ROOT(_t163);
    for (mrb_int _t164 = 0; _t164 < sp_IntArray_length(_t163); _t164++) {
      lv_p = sp_IntArray_get(_t163, _t164);
      lv_g = sp_IntArray_get(sp_TransformerLM_vectors_of(self, lv_grads), _t164);
      sp_TransformerLM_adam_step_vec_bang(self, lv_p, lv_g, lv_m, lv_v, lv_lr, lv_beta1, lv_beta2, lv_eps, lv_bc1, lv_bc2);
    }
    return NULL;
  return NULL;
}

static mrb_int sp_TransformerLM_train(sp_TransformerLM *self, mrb_int lv_sequences, mrb_int lv_epochs, mrb_int lv_learning_rate, mrb_int lv_batch_size) {
    SP_GC_SAVE();
    mrb_int lv_started = 0;
    mrb_int lv_epoch = 0;
    mrb_float lv_total_loss = 0.0;
    mrb_int lv_n = 0;
    sp_IntArray * lv_batch = NULL;
    sp_SymPolyHash * lv_acc = NULL;
    mrb_int lv_seq = 0;
    sp_SymPolyHash * lv_grads = NULL;
    SP_GC_ROOT(lv_batch);
    SP_GC_ROOT(lv_acc);
    SP_GC_ROOT(lv_grads);
    SP_GC_ROOT(self);
    { const char *_ps = (const char *)((&("\xff" "Training transformer LM")[1])); if (_ps) { fputs(_ps, stdout); if (!*_ps || _ps[strlen(_ps)-1] != '\n') putchar('\n'); } else putchar('\n'); }
    { const char *_ps = (const char *)(sp_sprintf("")); if (_ps) { fputs(_ps, stdout); if (!*_ps || _ps[strlen(_ps)-1] != '\n') putchar('\n'); } else putchar('\n'); }
    { const char *_ps = (const char *)(sp_sprintf("  examples=%lld  epochs=%lld  lr=%lld  batch=%lld", (long long)0, (long long)lv_epochs, (long long)lv_learning_rate, (long long)lv_batch_size)); if (_ps) { fputs(_ps, stdout); if (!*_ps || _ps[strlen(_ps)-1] != '\n') putchar('\n'); } else putchar('\n'); }
    lv_started = ((mrb_int)time(NULL));
    for (mrb_int _t165 = 0; _t165 < lv_epochs; _t165++) {
      lv_epoch = _t165;
      lv_total_loss = 0.0;
      lv_n = 0;
      mrb_int _t168 = sp_IntArray_length(0);
      for (mrb_int _t166 = 0; _t166 < _t168; _t166 += lv_batch_size) {
        lv_batch = sp_IntArray_new();
        for (mrb_int _t167 = 0; _t167 < lv_batch_size && _t166 + _t167 < _t168; _t167++)
          sp_IntArray_push(lv_batch, sp_IntArray_get(0, _t166 + _t167));
        lv_acc = sp_TransformerLM_zero_gradients(self);
        sp_TransformerLM_scale_gradients_bang(self, lv_acc, (1.0 / 0));
        sp_TransformerLM_apply_gradients(self, lv_acc, lv_learning_rate);
      }
      sp_IntArray *_t169 = sp_IntArray_new();
      sp_IntArray_push(_t169, lv_n);
      sp_IntArray_push(_t169, 1);
      { const char *_ps = (const char *)(sp_sprintf("Epoch %lld/%lld  mean_loss=%lld", (long long)(lv_epoch + 1), (long long)lv_epochs, (long long)(mrb_int)round((lv_total_loss / sp_IntArray_max(_t169))))); if (_ps) { fputs(_ps, stdout); if (!*_ps || _ps[strlen(_ps)-1] != '\n') putchar('\n'); } else putchar('\n'); }
    }
    { const char *_ps = (const char *)(sp_sprintf("Training completed in %llds", (long long)0)); if (_ps) { fputs(_ps, stdout); if (!*_ps || _ps[strlen(_ps)-1] != '\n') putchar('\n'); } else putchar('\n'); }
    return 0;
  return 0;
}

static const char * sp_TransformerLM_generate(sp_TransformerLM *self, mrb_int lv_prompt, mrb_int lv_max_tokens, mrb_float lv_temperature) {
    SP_GC_SAVE();
    sp_IntArray * lv_tokens = NULL;
    sp_SymPolyHash * lv_cache = NULL;
    mrb_int lv_logits = 0;
    sp_StrArray * lv_out = NULL;
    mrb_int lv_next_id = 0;
    SP_GC_ROOT(lv_tokens);
    SP_GC_ROOT(lv_cache);
    SP_GC_ROOT(lv_out);
    SP_GC_ROOT(self);
    lv_tokens = sp_TransformerLM_text_to_token_ids(self, lv_prompt);
    if (sp_IntArray_empty(lv_tokens)) {
      sp_IntArray *_t170 = sp_IntArray_new();
      sp_IntArray_push(_t170, 0);
      lv_tokens = _t170;
    }
    lv_cache = sp_TransformerLM_empty_kv_cache(self);
    lv_logits = sp_TransformerLM_forward_with_cache(self, lv_tokens, lv_cache);
    lv_out = 0;
    for (mrb_int _t171 = 0; _t171 < lv_max_tokens; _t171++) {
      lv_next_id = sp_TransformerLM_sample_token(self, 0, lv_temperature);
      if (!(lv_next_id)) {
        break;
      }
      sp_StrArray_push(lv_out, 0);
      if ((sp_SymPolyHash_get((sp_SymPolyHash *)(lv_cache), SPS_pos_offset) >= self->iv_context_length)) {
        break;
      }
      sp_IntArray *_t172 = sp_IntArray_new();
      sp_IntArray_push(_t172, lv_next_id);
      lv_logits = sp_TransformerLM_forward_with_cache(self, _t172, lv_cache);
    }
    return sp_StrArray_join(lv_out, (&("\xff" " ")[1]));
  return (&("\xff")[1]);
}

static inline sp_SymPolyHash * sp_TransformerLM_empty_kv_cache(sp_TransformerLM *self) {
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    sp_SymPolyHash *_t173 = sp_SymPolyHash_new();
    sp_SymPolyHash_set(_t173, SPS_pos_offset, sp_box_int(0));
    sp_IntArray *_t174 = sp_IntArray_new();
    SP_GC_ROOT(_t174);
    for (mrb_int _t175 = 0; _t175 < self->iv_n_layers; _t175++) {
      sp_StrIntHash *_t176 = sp_StrIntHash_new();
      sp_IntArray *_t177 = sp_IntArray_new();
      SP_GC_ROOT(_t177);
      for (mrb_int _t178 = 0; _t178 < self->iv_n_heads; _t178++) {
        sp_IntArray_push(_t177, sp_IntArray_new());
      }
      sp_StrIntHash_set(_t176, sp_sym_to_s(SPS_k), _t177);
      sp_IntArray *_t179 = sp_IntArray_new();
      SP_GC_ROOT(_t179);
      for (mrb_int _t180 = 0; _t180 < self->iv_n_heads; _t180++) {
        sp_IntArray_push(_t179, sp_IntArray_new());
      }
      sp_StrIntHash_set(_t176, sp_sym_to_s(SPS_v), _t179);
      sp_IntArray_push(_t174, _t176);
    }
    sp_SymPolyHash_set(_t173, SPS_layers, sp_box_int(_t174));
    return _t173;
  return NULL;
}

static mrb_int sp_TransformerLM_forward_with_cache(sp_TransformerLM *self, sp_IntArray * lv_new_tokens, sp_SymPolyHash * lv_cache) {
    SP_GC_SAVE();
    sp_RbVal lv_start_pos = sp_box_nil();
    sp_IntArray * lv_x = NULL;
    mrb_int lv_block = 0;
    mrb_int lv_layer_idx = 0;
    mrb_int lv_layer_kv = 0;
    mrb_int lv_h = 0;
    mrb_int lv__ = 0;
    mrb_float lv_inv_sqrt = 0.0;
    sp_IntArray * lv_head_outs = NULL;
    mrb_int lv_head_idx = 0;
    mrb_int lv_q = 0;
    mrb_int lv_k = 0;
    mrb_int lv_v = 0;
    mrb_int lv_k_full = 0;
    mrb_int lv_v_full = 0;
    mrb_int lv_scores = 0;
    mrb_int lv_attn = 0;
    mrb_int lv_concat = 0;
    mrb_int lv_x_after_attn = 0;
    mrb_int lv_h2 = 0;
    mrb_int lv_pre = 0;
    mrb_int lv_hidden = 0;
    mrb_int lv_row = 0;
    mrb_int lv_ff_out = 0;
    mrb_int lv_x_normed = 0;
    SP_GC_ROOT(lv_x);
    SP_GC_ROOT(lv_head_outs);
    SP_GC_ROOT(self);
    SP_GC_ROOT(lv_new_tokens);
    SP_GC_ROOT(lv_cache);
    lv_start_pos = sp_SymPolyHash_get((sp_SymPolyHash *)(lv_cache), SPS_pos_offset);
    if (sp_poly_gt(sp_poly_add(lv_start_pos, sp_box_int(sp_IntArray_length(lv_new_tokens))), sp_box_int(self->iv_context_length))) {
      sp_raise((&("\xff" "context overflow")[1]));
    }
    lv_x = sp_TransformerLM_embed(self, lv_new_tokens, 0);
    for (mrb_int _t181 = 0; _t181 < sp_IntArray_length(self->iv_blocks); _t181++) {
      lv_block = sp_IntArray_get(self->iv_blocks, _t181);
      lv_layer_idx = _t181;
      const char *_t182 = "";
      if (sp_SymPolyHash_get((sp_SymPolyHash *)(lv_cache), SPS_layers).tag == SP_TAG_OBJ) {
      }
      lv_layer_kv = _t182;
      sp_IntArray *_t183 = sp_TransformerLM_rms_norm(self, lv_x, 0);
      SP_GC_ROOT(_t183);
      lv_h = sp_IntArray_get(_t183, 0);
      lv__ = sp_IntArray_get(_t183, 1);
      lv_inv_sqrt = (1.0 / sqrt(self->iv_d_head));
      sp_IntArray *_t184 = sp_IntArray_new();
      SP_GC_ROOT(_t184);
      for (mrb_int _t185 = 0; _t185 < self->iv_n_heads; _t185++) {
        lv_head_idx = _t185;
        lv_q = 0;
        lv_k = 0;
        lv_v = 0;
        lv_k_full = 0;
        lv_v_full = 0;
        lv_scores = 0;
        sp_TransformerLM_apply_causal_mask_bang(self, lv_scores, 0);
        lv_attn = 0;
        sp_IntArray_push(_t184, 0);
      }
      lv_head_outs = _t184;
      lv_concat = 0;
      lv_x_after_attn = 0;
      sp_IntArray *_t186 = sp_TransformerLM_rms_norm(self, lv_x_after_attn, 0);
      SP_GC_ROOT(_t186);
      lv_h2 = sp_IntArray_get(_t186, 0);
      lv__ = sp_IntArray_get(_t186, 1);
      lv_pre = 0;
      mrb_int _t187 = lv_pre;
      lv_hidden = 0;
      lv_ff_out = 0;
      lv_x = 0;
    }
    sp_IntArray *_t190 = sp_TransformerLM_rms_norm(self, lv_x, self->iv_norm_final_gamma);
    SP_GC_ROOT(_t190);
    lv_x_normed = sp_IntArray_get(_t190, 0);
    lv__ = sp_IntArray_get(_t190, 1);
    return 0;
  return 0;
}

static mrb_int sp_TransformerLM_sample_token(sp_TransformerLM *self, mrb_int lv_logits_row, mrb_float lv_temperature) {
    SP_GC_SAVE();
    mrb_int lv_v = 0;
    mrb_int lv__ = 0;
    mrb_int lv_mx = 0;
    sp_FloatArray * lv_exp = NULL;
    mrb_float lv_sum = 0.0;
    sp_IntArray * lv_probs = NULL;
    mrb_float lv_e = 0.0;
    mrb_int lv_r = 0;
    mrb_float lv_cum = 0.0;
    mrb_int lv_p = 0;
    mrb_int lv_i = 0;
    SP_GC_ROOT(lv_exp);
    SP_GC_ROOT(lv_probs);
    SP_GC_ROOT(self);
    if ((lv_temperature <= 0)) {
      mrb_int _t191 = 0;
      SP_GC_RESTORE();
      return _t191;
    }
    lv_mx = 0;
    mrb_int _t192 = lv_logits_row;
    lv_exp = 0;
    lv_sum = sp_FloatArray_sum(lv_exp);
    sp_FloatArray * _t195 = lv_exp;
    lv_probs = 0;
    lv_r = ((mrb_int)rand());
    lv_cum = 0.0;
    for (mrb_int _t198 = 0; _t198 < sp_FloatArray_length(lv_probs); _t198++) {
      lv_p = sp_FloatArray_get(lv_probs, _t198);
      lv_i = _t198;
      lv_cum += lv_p;
      if ((lv_r < lv_cum)) {
        mrb_int _t199 = lv_i;
        SP_GC_RESTORE();
        return _t199;
      }
    }
    return (sp_FloatArray_length(lv_probs) - 1);
  return 0;
}

static inline mrb_int sp_TransformerLM_save_to_file(sp_TransformerLM *self, mrb_int lv_filename) {
    mrb_int lv_f = 0;
    mrb_int lv_w = 0;
    mrb_int lv_name = 0;
    mrb_int lv_m = 0;
    mrb_int lv_row = 0;
    mrb_int lv_v = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    { FILE *_t200 = fopen(lv_filename, (&("\xff" "w")[1]));
    if (_t200) {
    fprintf(_t200, "%s\n", sp_sprintf("HEADER %lld %lld %lld %lld %lld %lld", (long long)self->iv_vocab_size, (long long)self->iv_d_model, (long long)self->iv_d_ff, (long long)self->iv_n_heads, (long long)self->iv_context_length, (long long)self->iv_n_layers));
    fprintf(_t200, "%s\n", (&("\xff" "VOCAB")[1]));
    fprintf(_t200, "%s\n", (&("\xff" "END_VOCAB")[1]));
    sp_IntArray * _t201 = sp_TransformerLM_named_matrices(self);
    SP_GC_ROOT(_t201);
    for (mrb_int _t202 = 0; _t202 < sp_IntArray_length(_t201); _t202++) {
      lv_name = sp_IntArray_get(_t201, _t202);
    }
    sp_IntArray * _t203 = sp_TransformerLM_named_vectors(self);
    SP_GC_ROOT(_t203);
    for (mrb_int _t204 = 0; _t204 < sp_IntArray_length(_t203); _t204++) {
      lv_name = sp_IntArray_get(_t203, _t204);
    }
    fprintf(_t200, "%s\n", (&("\xff" "END")[1]));
    fclose(_t200);
    } }
    { const char *_ps = (const char *)(sp_sprintf("Network saved to %lld", (long long)lv_filename)); if (_ps) { fputs(_ps, stdout); if (!*_ps || _ps[strlen(_ps)-1] != '\n') putchar('\n'); } else putchar('\n'); }
    return 0;
  return 0;
}

static inline sp_IntArray * sp_TransformerLM_named_matrices(sp_TransformerLM *self) {
    SP_GC_SAVE();
    sp_IntArray * lv_pairs = NULL;
    mrb_int lv_b = 0;
    mrb_int lv_i = 0;
    mrb_int lv_h = 0;
    SP_GC_ROOT(lv_pairs);
    SP_GC_ROOT(self);
    sp_IntArray *_t205 = sp_IntArray_new();
    sp_PolyArray *_t206 = sp_PolyArray_new();
    sp_PolyArray_push(_t206, sp_box_str((&("\xff" "token_embed")[1])));
    sp_PolyArray_push(_t206, sp_box_int(self->iv_token_embed));
    sp_IntArray_push(_t205, _t206);
    sp_PolyArray *_t207 = sp_PolyArray_new();
    sp_PolyArray_push(_t207, sp_box_str((&("\xff" "pos_embed")[1])));
    sp_PolyArray_push(_t207, sp_box_int(self->iv_pos_embed));
    sp_IntArray_push(_t205, _t207);
    sp_PolyArray *_t208 = sp_PolyArray_new();
    sp_PolyArray_push(_t208, sp_box_str((&("\xff" "lm_head")[1])));
    sp_PolyArray_push(_t208, sp_box_int(self->iv_lm_head));
    sp_IntArray_push(_t205, _t208);
    lv_pairs = _t205;
    for (mrb_int _t209 = 0; _t209 < sp_IntArray_length(self->iv_blocks); _t209++) {
      lv_b = sp_IntArray_get(self->iv_blocks, _t209);
      lv_i = _t209;
      for (mrb_int _t210 = 0; _t210 < self->iv_n_heads; _t210++) {
        lv_h = _t210;
        sp_PolyArray *_t211 = sp_PolyArray_new();
        sp_PolyArray_push(_t211, sp_box_str(sp_sprintf("block_%lld_w_q_%lld", (long long)lv_i, (long long)lv_h)));
        sp_PolyArray_push(_t211, sp_box_int(0));
        sp_IntArray_push(lv_pairs, _t211);
        sp_PolyArray *_t212 = sp_PolyArray_new();
        sp_PolyArray_push(_t212, sp_box_str(sp_sprintf("block_%lld_w_k_%lld", (long long)lv_i, (long long)lv_h)));
        sp_PolyArray_push(_t212, sp_box_int(0));
        sp_IntArray_push(lv_pairs, _t212);
        sp_PolyArray *_t213 = sp_PolyArray_new();
        sp_PolyArray_push(_t213, sp_box_str(sp_sprintf("block_%lld_w_v_%lld", (long long)lv_i, (long long)lv_h)));
        sp_PolyArray_push(_t213, sp_box_int(0));
        sp_IntArray_push(lv_pairs, _t213);
      }
      sp_PolyArray *_t214 = sp_PolyArray_new();
      sp_PolyArray_push(_t214, sp_box_str(sp_sprintf("block_%lld_w_o", (long long)lv_i)));
      sp_PolyArray_push(_t214, sp_box_int(0));
      sp_IntArray_push(lv_pairs, _t214);
      sp_PolyArray *_t215 = sp_PolyArray_new();
      sp_PolyArray_push(_t215, sp_box_str(sp_sprintf("block_%lld_w_ff1", (long long)lv_i)));
      sp_PolyArray_push(_t215, sp_box_int(0));
      sp_IntArray_push(lv_pairs, _t215);
      sp_PolyArray *_t216 = sp_PolyArray_new();
      sp_PolyArray_push(_t216, sp_box_str(sp_sprintf("block_%lld_w_ff2", (long long)lv_i)));
      sp_PolyArray_push(_t216, sp_box_int(0));
      sp_IntArray_push(lv_pairs, _t216);
    }
    return lv_pairs;
  return NULL;
}

static inline sp_IntArray * sp_TransformerLM_named_vectors(sp_TransformerLM *self) {
    SP_GC_SAVE();
    sp_IntArray * lv_pairs = NULL;
    mrb_int lv_b = 0;
    mrb_int lv_i = 0;
    SP_GC_ROOT(lv_pairs);
    SP_GC_ROOT(self);
    sp_IntArray *_t217 = sp_IntArray_new();
    sp_PolyArray *_t218 = sp_PolyArray_new();
    sp_PolyArray_push(_t218, sp_box_str((&("\xff" "norm_final_gamma")[1])));
    sp_PolyArray_push(_t218, sp_box_int(self->iv_norm_final_gamma));
    sp_IntArray_push(_t217, _t218);
    lv_pairs = _t217;
    for (mrb_int _t219 = 0; _t219 < sp_IntArray_length(self->iv_blocks); _t219++) {
      lv_b = sp_IntArray_get(self->iv_blocks, _t219);
      lv_i = _t219;
      sp_PolyArray *_t220 = sp_PolyArray_new();
      sp_PolyArray_push(_t220, sp_box_str(sp_sprintf("block_%lld_norm1_gamma", (long long)lv_i)));
      sp_PolyArray_push(_t220, sp_box_int(0));
      sp_IntArray_push(lv_pairs, _t220);
      sp_PolyArray *_t221 = sp_PolyArray_new();
      sp_PolyArray_push(_t221, sp_box_str(sp_sprintf("block_%lld_norm2_gamma", (long long)lv_i)));
      sp_PolyArray_push(_t221, sp_box_int(0));
      sp_IntArray_push(lv_pairs, _t221);
    }
    return lv_pairs;
  return NULL;
}

static inline mrb_int sp_TransformerLM_set_named_matrix(sp_TransformerLM *self, mrb_int lv_name, mrb_int lv_matrix) {
    mrb_int lv_m = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    mrb_int _t222 = lv_name;
    if (_t222 == (&("\xff" "token_embed")[1])) {
      self->iv_token_embed = lv_matrix;
      return 0;
    } else if (_t222 == (&("\xff" "pos_embed")[1])) {
      self->iv_pos_embed = lv_matrix;
      return 0;
    } else if (_t222 == (&("\xff" "lm_head")[1])) {
      self->iv_lm_head = lv_matrix;
      return 0;
    } else {
      lv_m = 0;
      if (lv_m) {
        SP_GC_RESTORE();
        return 0;
      }
      lv_m = 0;
      if (!(lv_m)) {
        sp_raise(sp_sprintf("unknown matrix %lld", (long long)lv_name));
      }
      return 0;
    }
  return 0;
}

static mrb_int sp_TransformerLM_set_named_vector(sp_TransformerLM *self, mrb_int lv_name, mrb_int lv_vec) {
    mrb_int lv_m = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    if ((lv_name == (&("\xff" "norm_final_gamma")[1]))) {
      self->iv_norm_final_gamma = lv_vec;
      SP_GC_RESTORE();
      return 0;
    }
    lv_m = 0;
    if (!(lv_m)) {
      sp_raise(sp_sprintf("unknown vector %lld", (long long)lv_name));
    }
    return 0;
  return 0;
}

static inline sp_SymPolyHash * sp_TransformerLM_model_size(sp_TransformerLM *self) {
    mrb_int lv_count = 0;
    mrb_int lv_m = 0;
    mrb_int lv__spx = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    sp_IntArray * _t223 = sp_TransformerLM_matrices_of(self, sp_TransformerLM_model_struct(self));
    SP_GC_ROOT(_t223);
    mrb_int _t224 = 0;
    for (mrb_int _t225 = 0; _t225 < sp_IntArray_length(_t223); _t225++) {
      lv_m = sp_IntArray_get(_t223, _t225);
      _t224 += (0 * 0);
    }
    lv_count = _t224;
    sp_IntArray * _t226 = sp_TransformerLM_vectors_of(self, sp_TransformerLM_model_struct(self));
    SP_GC_ROOT(_t226);
    mrb_int _t227 = 0;
    for (mrb_int _t228 = 0; _t228 < sp_IntArray_length(_t226); _t228++) {
      lv__spx = sp_IntArray_get(_t226, _t228);
      _t227 += 0;
    }
    lv_count += _t227;
    sp_SymPolyHash *_t229 = sp_SymPolyHash_new();
    sp_SymPolyHash_set(_t229, SPS_parameters, sp_box_int(lv_count));
    sp_SymPolyHash_set(_t229, SPS_memory_kb, sp_box_int((mrb_int)round(((mrb_float)(lv_count * 4) / 1024.0))));
    sp_SymIntHash *_t230 = sp_SymIntHash_new();
    sp_SymIntHash_set(_t230, SPS_vocab, self->iv_vocab_size);
    sp_SymIntHash_set(_t230, SPS_d_model, self->iv_d_model);
    sp_SymIntHash_set(_t230, SPS_d_ff, self->iv_d_ff);
    sp_SymIntHash_set(_t230, SPS_n_heads, self->iv_n_heads);
    sp_SymIntHash_set(_t230, SPS_n_layers, self->iv_n_layers);
    sp_SymIntHash_set(_t230, SPS_context, self->iv_context_length);
    sp_SymPolyHash_set(_t229, SPS_layers, sp_box_int(_t230));
    return _t229;
  return NULL;
}

static inline mrb_int sp_TransformerLM_add_vec_bang(sp_TransformerLM *self, mrb_int lv_a, mrb_int lv_b) {
    mrb_int lv_i = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    for (mrb_int _t231 = 0; _t231 < 0; _t231++) {
      lv_i = _t231;
    }
    return lv_a;
  return 0;
}

static inline mrb_int sp_TransformerLM_scale_vec_bang(sp_TransformerLM *self, mrb_int lv_a, mrb_float lv_s) {
    mrb_int lv_i = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    for (mrb_int _t232 = 0; _t232 < 0; _t232++) {
      lv_i = _t232;
    }
    return lv_a;
  return 0;
}

static inline mrb_int sp_TransformerLM_adam_step_bang(sp_TransformerLM *self, mrb_int lv_param, mrb_int lv_grad, mrb_int lv_m, mrb_int lv_v, mrb_int lv_lr, mrb_float lv_b1, mrb_float lv_b2, mrb_float lv_eps, mrb_float lv_bc1, mrb_float lv_bc2) {
    mrb_int lv_rows = 0;
    mrb_int lv_cols = 0;
    mrb_int lv_i = 0;
    mrb_int lv_pi = 0;
    mrb_int lv_gi = 0;
    mrb_int lv_mi = 0;
    mrb_int lv_vi = 0;
    mrb_int lv_j = 0;
    mrb_int lv_g = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    lv_rows = 0;
    lv_cols = 0;
    for (mrb_int _t233 = 0; _t233 < lv_rows; _t233++) {
      lv_i = _t233;
      mrb_int _t234 = 0;
      mrb_int _t235 = 0;
      mrb_int _t236 = 0;
      mrb_int _t237 = 0;
      lv_pi = _t234;
      lv_gi = _t235;
      lv_mi = _t236;
      lv_vi = _t237;
      for (mrb_int _t238 = 0; _t238 < lv_cols; _t238++) {
        lv_j = _t238;
        lv_g = 0;
      }
    }
    return 0;
  return 0;
}

static inline mrb_int sp_TransformerLM_adam_step_vec_bang(sp_TransformerLM *self, mrb_int lv_param, mrb_int lv_grad, mrb_int lv_m, mrb_int lv_v, mrb_int lv_lr, mrb_float lv_b1, mrb_float lv_b2, mrb_float lv_eps, mrb_float lv_bc1, mrb_float lv_bc2) {
    mrb_int lv_i = 0;
    mrb_int lv_g = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    for (mrb_int _t239 = 0; _t239 < 0; _t239++) {
      lv_i = _t239;
      lv_g = 0;
    }
    return 0;
  return 0;
}

static sp_IntArray * sp_TransformerLM_cls_create_from_data(mrb_int lv_data, mrb_int lv_d_model, mrb_int lv_d_ff, mrb_int lv_n_heads, mrb_int lv_context_length, mrb_int lv_n_layers) {
    mrb_int lv_words = 0;
    mrb_int lv_line = 0;
    mrb_int lv_word_to_index = 0;
    mrb_int lv_nn = 0;
    mrb_int lv_sequences = 0;
    mrb_int lv_s = 0;
    mrb_int_t240 = sp_IntArray_new();
    for (mrb_int _t241 = 0; _t241 < sp_IntArray_length(lv_data); _t241++) {
      lv_line = sp_IntArray_get(lv_data, _t241);
      mrb_int_t242 = 0;
      for (mrb_int _t243 = 0; _t243 < sp_IntArray_length(_t242); _t243++)
        sp_IntArray_push(_t240, sp_IntArray_get(_t242, _t243));
    }
    lv_words = 0;
    lv_word_to_index = 0;
    lv_nn = 0;
    mrb_int _t244 = lv_data;
    mrb_int _t247 = lv_data;
    lv_sequences = 0;
    sp_IntArray *_t250 = sp_IntArray_new();
    sp_IntArray_push(_t250, lv_nn);
    sp_IntArray_push(_t250, lv_sequences);
    return _t250;
  return NULL;
}

static mrb_int sp_TransformerLM_cls_load_from_file(mrb_int lv_filename) {
    SP_GC_SAVE();
    sp_StrArray * lv_lines = NULL;
    mrb_int lv_i = 0;
    sp_StrArray * lv_header_parts = NULL;
    mrb_int lv_vocab_size = 0;
    mrb_int lv_d_model = 0;
    mrb_int lv_d_ff = 0;
    mrb_int lv_n_heads = 0;
    mrb_int lv_context = 0;
    mrb_int lv_n_layers = 0;
    const char * lv__spx = (&("\xff")[1]);
    sp_StrArray * lv_vocabulary = NULL;
    mrb_int lv_word_to_index = 0;
    mrb_int lv_nn = 0;
    sp_StrArray * lv_tag = NULL;
    mrb_int lv_name = 0;
    mrb_int lv_rows = 0;
    mrb_int lv_cols = 0;
    sp_IntArray * lv_matrix = NULL;
    mrb_int lv_r = 0;
    mrb_int lv_len = 0;
    sp_FloatArray * lv_vec = NULL;
    SP_GC_ROOT(lv_lines);
    SP_GC_ROOT(lv_header_parts);
    SP_GC_ROOT(lv__spx);
    SP_GC_ROOT(lv_vocabulary);
    SP_GC_ROOT(lv_tag);
    SP_GC_ROOT(lv_matrix);
    SP_GC_ROOT(lv_vec);
    lv_lines = 0;
    lv_i = 0;
    const char * _t251 = sp_StrArray_get(lv_lines, lv_i);
    SP_GC_ROOT(_t251);
    lv_header_parts = sp_str_split(_t251, 0);
    if (!((strcmp(sp_StrArray_get(lv_header_parts, 0), (&("\xff" "HEADER")[1])) == 0))) {
      sp_raise((&("\xff" "bad header")[1]));
    }
    sp_StrArray * _t253 = sp_StrArray_slice(lv_header_parts, 1, 6 - 1 + 1);
    SP_GC_ROOT(_t253);
    sp_StrArray * _t254 = sp_StrArray_slice(lv_header_parts, 1, 6 - 1 + 1);
    sp_IntArray *_t255 = sp_IntArray_new();
    for (mrb_int _t256 = 0; _t256 < sp_StrArray_length(_t254); _t256++) {
      const char *lv__spx = sp_StrArray_get(_t254, _t256);
      sp_IntArray_push(_t255, ((mrb_int)atoll(lv__spx)));
    }
    sp_IntArray *_t252 = _t255;
    SP_GC_ROOT(_t252);
    lv_vocab_size = sp_IntArray_get(_t252, 0);
    lv_d_model = sp_IntArray_get(_t252, 1);
    lv_d_ff = sp_IntArray_get(_t252, 2);
    lv_n_heads = sp_IntArray_get(_t252, 3);
    lv_context = sp_IntArray_get(_t252, 4);
    lv_n_layers = sp_IntArray_get(_t252, 5);
    lv_i += 1;
    if (!((strcmp(sp_StrArray_get(lv_lines, lv_i), (&("\xff" "VOCAB")[1])) == 0))) {
      sp_raise((&("\xff" "expected VOCAB")[1]));
    }
    lv_i += 1;
    lv_vocabulary = sp_StrArray_new();
    while ((strcmp(sp_StrArray_get(lv_lines, lv_i), (&("\xff" "END_VOCAB")[1])) != 0)) {
      sp_StrArray_push(lv_vocabulary, sp_StrArray_get(lv_lines, lv_i));
      lv_i += 1;
    }
    lv_i += 1;
    lv_word_to_index = 0;
    lv_nn = 0;
    while ((strcmp(sp_StrArray_get(lv_lines, lv_i), (&("\xff" "END")[1])) != 0)) {
      if (lv_tag == NULL) lv_tag = sp_str_split(sp_StrArray_get(lv_lines, lv_i), 0);
      else sp_str_split_into(lv_tag, sp_StrArray_get(lv_lines, lv_i), 0);
      const char *_t257 = sp_StrArray_get(lv_tag, 0);
      if (strcmp(_t257, (&("\xff" "M")[1])) == 0) {
        const char * _t258 = sp_StrArray_get(lv_tag, 1);
        const char * _t260 = sp_StrArray_get(lv_tag, 2);
        SP_GC_ROOT(_t260);
        mrb_int _t259 = ((mrb_int)atoll(_t260));
        const char * _t262 = sp_StrArray_get(lv_tag, 3);
        SP_GC_ROOT(_t262);
        mrb_int _t261 = ((mrb_int)atoll(_t262));
        lv_name = _t258;
        lv_rows = _t259;
        lv_cols = _t261;
        lv_i += 1;
        sp_IntArray *_t263 = sp_IntArray_new();
        SP_GC_ROOT(_t263);
        for (mrb_int _t264 = 0; _t264 < lv_rows; _t264++) {
          lv_r = _t264;
          const char * _t265 = sp_StrArray_get(lv_lines, (lv_i + lv_r));
          SP_GC_ROOT(_t265);
          sp_StrArray * _t266 = sp_str_split(_t265, 0);
          SP_GC_ROOT(_t266);
          const char * _t267 = sp_StrArray_get(lv_lines, (lv_i + lv_r));
          SP_GC_ROOT(_t267);
          sp_StrArray * _t268 = sp_str_split(_t267, 0);
          sp_StrArray *_t269 = sp_StrArray_new();
          for (mrb_int _t270 = 0; _t270 < sp_StrArray_length(_t268); _t270++) {
            const char *lv__spx = sp_StrArray_get(_t268, _t270);
            sp_StrArray_push(_t269, atof(lv__spx));
          }
          sp_IntArray_push(_t263, _t269);
        }
        lv_matrix = _t263;
        if ((0 != lv_cols)) {
          sp_raise((&("\xff" "matrix col mismatch")[1]));
        }
        lv_i += lv_rows;
        sp_TransformerLM_set_named_matrix((sp_TransformerLM *)lv_nn, lv_name, lv_matrix);
      } else if (strcmp(_t257, (&("\xff" "V")[1])) == 0) {
        const char * _t271 = sp_StrArray_get(lv_tag, 1);
        const char * _t273 = sp_StrArray_get(lv_tag, 2);
        SP_GC_ROOT(_t273);
        mrb_int _t272 = ((mrb_int)atoll(_t273));
        lv_name = _t271;
        lv_len = _t272;
        lv_i += 1;
        const char * _t274 = sp_StrArray_get(lv_lines, lv_i);
        SP_GC_ROOT(_t274);
        sp_StrArray * _t275 = sp_str_split(_t274, 0);
        SP_GC_ROOT(_t275);
        const char * _t276 = sp_StrArray_get(lv_lines, lv_i);
        SP_GC_ROOT(_t276);
        sp_StrArray * _t277 = sp_str_split(_t276, 0);
        sp_StrArray *_t278 = sp_StrArray_new();
        for (mrb_int _t279 = 0; _t279 < sp_StrArray_length(_t277); _t279++) {
          const char *lv__spx = sp_StrArray_get(_t277, _t279);
          sp_StrArray_push(_t278, atof(lv__spx));
        }
        lv_vec = _t278;
        if (!((sp_FloatArray_length(lv_vec) == lv_len))) {
          sp_raise(sp_sprintf("vec length mismatch (%lld != %lld)", (long long)sp_FloatArray_length(lv_vec), (long long)lv_len));
        }
        lv_i += 1;
        sp_TransformerLM_set_named_vector((sp_TransformerLM *)lv_nn, lv_name, lv_vec);
      } else {
        sp_raise(sp_sprintf("unknown tag %s", sp_StrArray_get(lv_tag, 0)));
      }
    }
    { const char *_ps = (const char *)(sp_sprintf("Network loaded from %lld", (long long)lv_filename)); if (_ps) { fputs(_ps, stdout); if (!*_ps || _ps[strlen(_ps)-1] != '\n') putchar('\n'); } else putchar('\n'); }
    return lv_nn;
  return 0;
}

typedef struct{const char**data;mrb_int len;}sp_Argv;
static sp_Argv sp_argv;

int main(int argc,char**argv){
  sp_argv.len=argc-1;sp_argv.data=(const char**)malloc(sizeof(const char*)*(argc>1?argc-1:1));{int _i;for(_i=0;_i<sp_argv.len;_i++)sp_argv.data[_i]=sp_str_dup_external(argv[_i+1]);}
  srand((unsigned)time(NULL));
  sp_re_init();
    SP_GC_SAVE();
    volatile const char *lv_text = (&("\xff")[1]);
    SP_GC_ROOT(lv_text);
    volatile sp_StrArray *lv_tokens = NULL;
    SP_GC_ROOT(lv_tokens);
    volatile sp_IntArray *lv_out = NULL;
    SP_GC_ROOT(lv_out);
    volatile const char *lv_token = (&("\xff")[1]);
    SP_GC_ROOT(lv_token);
    volatile mrb_int lv_i = 0;
    volatile const char *lv_t = (&("\xff")[1]);
    SP_GC_ROOT(lv_t);
    volatile mrb_int lv_rows = 0;
    volatile mrb_int lv_inner = 0;
    volatile mrb_int lv_cols = 0;
    volatile mrb_int lv_ai = 0;
    volatile mrb_int lv_k = 0;
    volatile mrb_int lv_aik = 0;
    volatile mrb_int lv_bk = 0;
    volatile mrb_int lv_j = 0;
    volatile mrb_int lv_row = 0;
    volatile mrb_int lv_v = 0;
    volatile mrb_int lv_mx = 0;
    volatile sp_FloatArray *lv_exp = NULL;
    SP_GC_ROOT(lv_exp);
    volatile mrb_int lv_sum = 0;
    volatile mrb_float lv_e = 0.0;
    volatile mrb_int lv__ = 0;
    volatile mrb_int lv_m = 0;
    volatile mrb_int lv_chunk = 0;
    volatile mrb_int lv_c = 0;
    volatile mrb_int lv_nn = 0;
    volatile mrb_int lv_sequences = 0;
    sp_StrArray *_t280 = sp_StrArray_new();
    sp_StrArray_push(_t280, (&("\xff" "un est deux")[1]));
    sp_StrArray_push(_t280, (&("\xff" "deux est trois")[1]));
    sp_StrArray_push(_t280, (&("\xff" "trois est quatre")[1]));
    sp_StrArray_push(_t280, (&("\xff" "quatre est cinq")[1]));
    sp_StrArray_push(_t280, (&("\xff" "cinq est six")[1]));
    cst_CORPUS = _t280;
    SP_GC_ROOT(cst_CORPUS);

    srand((unsigned)42);
    sp_IntArray *_t281 = sp_TransformerLM_cls_create_from_data(cst_CORPUS, 0);
    SP_GC_ROOT(_t281);
    lv_nn = sp_IntArray_get(_t281, 0);
    lv_sequences = sp_IntArray_get(_t281, 1);
    sp_TransformerLM_train((sp_TransformerLM *)lv_nn, lv_sequences, 0);
    { const char *_ps = (const char *)((&("\xff" "")[1])); if (_ps) { fputs(_ps, stdout); if (!*_ps || _ps[strlen(_ps)-1] != '\n') putchar('\n'); } else putchar('\n'); }
    { const char *_ps = (const char *)((&("\xff" "Generation from 'un est':")[1])); if (_ps) { fputs(_ps, stdout); if (!*_ps || _ps[strlen(_ps)-1] != '\n') putchar('\n'); } else putchar('\n'); }
    { const char *_ps = (const char *)(sp_TransformerLM_generate((sp_TransformerLM *)lv_nn, (&("\xff" "un est")[1]), 0)); if (_ps) { fputs(_ps, stdout); if (!*_ps || _ps[strlen(_ps)-1] != '\n') putchar('\n'); } else putchar('\n'); }
  return 0;
}
